// More cases: Telecommunications, Broad-Based BEE, Water, Housing, Policing, Access to Justice, Equality
module.exports = [
  // ── TELECOMMUNICATIONS / ICT ──────────────────────────────────────────
  { title: "Altech Autopage Cellular v Chairperson of the Council of ICASA", citation: "[2008] ZASCA 84", court: "Supreme Court of Appeal", year: 2008, tags: ["administrative"], url: "https://www.saflii.org/za/cases/ZASCA/2008/84.html", summary: "Telecommunications licensing; ICASA's regulatory powers and obligation to follow fair procedure." },
  { title: "Cell C v ICASA", citation: "[2014] ZAGPPHC 756", court: "Gauteng High Court, Pretoria", year: 2014, tags: ["administrative","competition"], url: "https://www.saflii.org/za/cases/ZAGPPHC/2014/756.html", summary: "Call termination rates regulation; ICASA's power to regulate interconnection and promote competition." },
  { title: "Electronic Media Network v e.tv", citation: "[2017] ZASCA 17", court: "Supreme Court of Appeal", year: 2017, tags: ["intellectual property"], url: "https://www.saflii.org/za/cases/ZASCA/2017/17.html", summary: "Broadcasting rights; exclusive content rights and competition in pay-TV market." },
  { title: "Media Workers Association v Press Council of SA", citation: "[2016] ZAGPJHC 2", court: "Gauteng High Court, Johannesburg", year: 2016, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZAGPJHC/2016/2.html", summary: "Press regulation; voluntary self-regulation system and its compatibility with press freedom." },

  // ── BEE / TRANSFORMATION ──────────────────────────────────────────────
  { title: "South African Airways v BDFM Publishers", citation: "[2016] ZAGPJHC 313", court: "Gauteng High Court, Johannesburg", year: 2016, tags: ["administrative"], url: "https://www.saflii.org/za/cases/ZAGPJHC/2016/313.html", summary: "BEE compliance; fronting practices and verification of BEE credentials in procurement." },
  { title: "Viking Pony Africa Pumps v Hidro-Tech Systems", citation: "[2010] ZASCA 145", court: "Supreme Court of Appeal", year: 2010, tags: ["administrative"], url: "https://www.saflii.org/za/cases/ZASCA/2010/145.html", summary: "BEE in public procurement; fraudulent BEE certificates and consequences for tender awards." },
  { title: "Minister of Finance v Afribusiness NPC", citation: "[2022] ZACC 4", court: "Constitutional Court", year: 2022, tags: ["administrative","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2022/4.html", summary: "Preferential Procurement Policy Framework Act regulations; Minister's power to prescribe BEE criteria." },

  // ── WATER ─────────────────────────────────────────────────────────────
  { title: "Federation for Sustainable Environment v Minister of Water Affairs", citation: "[2012] ZAGPPHC 128", court: "Gauteng High Court, Pretoria", year: 2012, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZAGPPHC/2012/128.html", summary: "Right to water; acid mine drainage and government's duty to ensure access to sufficient water." },
  { title: "City of Johannesburg v Mazibuko", citation: "[2009] ZASCA 20", court: "Supreme Court of Appeal", year: 2009, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZASCA/2009/20.html", summary: "Free basic water; municipality's obligation to provide minimum quantity of free water to residents." },
  { title: "Mostert v S", citation: "[2010] ZASCA 72", court: "Supreme Court of Appeal", year: 2010, tags: ["environmental","criminal"], url: "https://www.saflii.org/za/cases/ZASCA/2010/72.html", summary: "Water pollution as criminal offence; National Water Act offences for contaminating water resources." },

  // ── HOUSING ───────────────────────────────────────────────────────────
  { title: "Government of the RSA v Grootboom", citation: "[2000] ZACC 19", court: "Constitutional Court", year: 2000, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2000/19.html", summary: "Right to housing; government must have reasonable programme to provide access to adequate housing." },
  { title: "City of Johannesburg v Blue Moonlight Properties", citation: "[2011] ZACC 33", court: "Constitutional Court", year: 2011, tags: ["constitutional","property law"], url: "https://www.saflii.org/za/cases/ZACC/2011/33.html", summary: "Municipality's housing obligation on private land eviction; duty to provide temporary accommodation." },
  { title: "Sailing Queen Investments v The Occupants La Colleen Court", citation: "[2008] ZAKZDHC 11", court: "KwaZulu-Natal High Court, Durban", year: 2008, tags: ["property law"], url: "https://www.saflii.org/za/cases/ZAKZDHC/2008/11.html", summary: "PIE Act eviction; court must consider all relevant circumstances including availability of alternative accommodation." },
  { title: "Changing Tides 17 v Erasmus", citation: "[2018] ZAGPJHC 524", court: "Gauteng High Court, Johannesburg", year: 2018, tags: ["property law"], url: "https://www.saflii.org/za/cases/ZAGPJHC/2018/524.html", summary: "Sectional title eviction; body corporate enforcement of conduct rules against unit owners." },

  // ── POLICING / SECURITY ───────────────────────────────────────────────
  { title: "Mistry v Interim National Medical and Dental Council", citation: "[1998] ZACC 10", court: "Constitutional Court", year: 1998, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1998/10.html", summary: "Search without warrant; administrative inspection powers and privacy limitations for regulatory compliance." },
  { title: "Minister of Police v Kunjana", citation: "[2016] ZACC 21", court: "Constitutional Court", year: 2016, tags: ["delict","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2016/21.html", summary: "Unlawful arrest; SAPS liability for damages from wrongful detention without warrant." },
  { title: "De Klerk v Minister of Police", citation: "[2019] ZACC 32", court: "Constitutional Court", year: 2019, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZACC/2019/32.html", summary: "Police shooting liability; State delictual liability for off-duty police officer's use of service weapon." },
  { title: "Barkhuizen v Napier", citation: "[2007] ZACC 5", court: "Constitutional Court", year: 2007, tags: ["contract law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2007/5.html", summary: "Time-bar clauses; public policy, good faith and constitutional values in contractual enforcement." },
  { title: "Investigating Directorate v Hyundai Motor Distributors", citation: "[2000] ZACC 12", court: "Constitutional Court", year: 2000, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/2000/12.html", summary: "Search warrants under NPA Act; balance between effective investigation and right to privacy." },

  // ── ACCESS TO JUSTICE / LEGAL AID ─────────────────────────────────────
  { title: "S v Vermaas; S v Du Plessis", citation: "[1995] ZACC 4", court: "Constitutional Court", year: 1995, tags: ["criminal","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1995/4.html", summary: "Right to legal representation at State expense; section 35(3)(g) applies where substantial injustice would result." },
  { title: "Legal Aid SA v Magidiwana", citation: "[2015] ZASCA 28", court: "Supreme Court of Appeal", year: 2015, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZASCA/2015/28.html", summary: "Legal Aid mandate; obligation to provide legal representation in matters where liberty is at stake." },
  { title: "Magidiwana v President of the RSA", citation: "[2013] ZAGPPHC 292", court: "Gauteng High Court, Pretoria", year: 2013, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZAGPPHC/2013/292.html", summary: "Marikana commission; right to legal representation at commissions of inquiry where criminal liability may arise." },

  // ── EQUALITY / DISCRIMINATION ─────────────────────────────────────────
  { title: "Hoffmann v South African Airways", citation: "[2000] ZACC 17", court: "Constitutional Court", year: 2000, tags: ["constitutional","employment"], url: "https://www.saflii.org/za/cases/ZACC/2000/17.html", summary: "HIV discrimination in employment; refusal to employ cabin crew based on HIV status unfairly discriminatory." },
  { title: "National Coalition for Gay and Lesbian Equality v Minister of Justice", citation: "[1998] ZACC 15", court: "Constitutional Court", year: 1998, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/1998/15.html", summary: "Criminalisation of sodomy unconstitutional; sexual orientation discrimination under equality clause." },
  { title: "National Coalition for Gay and Lesbian Equality v Minister of Home Affairs", citation: "[1999] ZACC 17", court: "Constitutional Court", year: 1999, tags: ["constitutional","family law"], url: "https://www.saflii.org/za/cases/ZACC/1999/17.html", summary: "Same-sex partners' immigration benefits; Aliens Control Act extended to include same-sex life partners." },
  { title: "Minister of Finance v Van Heerden", citation: "[2004] ZACC 3", court: "Constitutional Court", year: 2004, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/3.html", summary: "Affirmative action under section 9(2); restitutionary measures to achieve substantive equality." },
  { title: "President of RSA v Hugo", citation: "[1997] ZACC 4", court: "Constitutional Court", year: 1997, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1997/4.html", summary: "Presidential pardon of mothers with children under 12; differentiation between fathers and mothers." },
  { title: "Prinsloo v Van der Linde", citation: "[1997] ZACC 5", court: "Constitutional Court", year: 1997, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1997/5.html", summary: "Equality and non-discrimination; mere differentiation vs unfair discrimination under section 9." },
  { title: "City Council of Pretoria v Walker", citation: "[1998] ZACC 1", court: "Constitutional Court", year: 1998, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1998/1.html", summary: "Indirect discrimination; differential enforcement of municipal by-laws along racial lines." },
  { title: "Volks NO v Robinson", citation: "[2005] ZACC 2", court: "Constitutional Court", year: 2005, tags: ["constitutional","family law"], url: "https://www.saflii.org/za/cases/ZACC/2005/2.html", summary: "Permanent life partner's maintenance claim against deceased estate; heterosexual cohabitant's rights." },

  // ── ELECTIONS / POLITICAL RIGHTS ───────────────────────────────────────
  { title: "New National Party v Government of RSA", citation: "[1999] ZACC 5", court: "Constitutional Court", year: 1999, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1999/5.html", summary: "Voter registration; requirement for bar-coded ID book as barrier to right to vote." },
  { title: "August v Electoral Commission", citation: "[1999] ZACC 3", court: "Constitutional Court", year: 1999, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1999/3.html", summary: "Prisoners' right to vote; blanket disenfranchisement of prisoners unconstitutional." },
  { title: "Minister of Home Affairs v NICRO", citation: "[2004] ZACC 10", court: "Constitutional Court", year: 2004, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/10.html", summary: "Sentenced prisoners' right to vote; Electoral Act provision denying vote to prisoners invalid." },
  { title: "Ramakatsa v Magashule", citation: "[2012] ZACC 31", court: "Constitutional Court", year: 2012, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2012/31.html", summary: "Political party internal democracy; court may intervene in party affairs when party constitution violated." },
  { title: "My Vote Counts NPC v Speaker of the National Assembly", citation: "[2015] ZACC 31", court: "Constitutional Court", year: 2015, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2015/31.html", summary: "Private funding of political parties; right to access information on party funding sources." },
];
