// Additional cases: Customary Law, Land Reform, Education, Health, Social Security
module.exports = [
  // ── CUSTOMARY LAW ─────────────────────────────────────────────────────
  { title: "Bhe v Khayelitsha Magistrate", citation: "[2004] ZACC 17", court: "Constitutional Court", year: 2004, tags: ["customary law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/17.html", summary: "Male primogeniture in customary law of succession invalidated as unfairly discriminating against women." },
  { title: "Shilubana v Nwamitwa", citation: "[2008] ZACC 9", court: "Constitutional Court", year: 2008, tags: ["customary law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2008/9.html", summary: "Traditional community may develop its customs; appointment of female chief upheld as living customary law." },
  { title: "Alexkor v Richtersveld Community", citation: "[2003] ZACC 18", court: "Constitutional Court", year: 2003, tags: ["customary law","property law"], url: "https://www.saflii.org/za/cases/ZACC/2003/18.html", summary: "Indigenous peoples' right to land; Richtersveld community entitled to restitution of mineral-rich ancestral land." },
  { title: "Pilane v Pilane", citation: "[2013] ZACC 1", court: "Constitutional Court", year: 2013, tags: ["customary law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2013/1.html", summary: "Traditional leadership disputes; courts may intervene where customary processes fail to resolve succession." },
  { title: "Mayelane v Ngwenyama", citation: "[2013] ZACC 14", court: "Constitutional Court", year: 2013, tags: ["customary law","family law"], url: "https://www.saflii.org/za/cases/ZACC/2013/14.html", summary: "Customary marriage; first wife's consent required for validity of subsequent customary marriage." },
  { title: "Gumede v President of the RSA", citation: "[2008] ZACC 23", court: "Constitutional Court", year: 2008, tags: ["customary law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2008/23.html", summary: "Proprietary consequences of customary marriages; KwaZulu Act discriminating against women invalidated." },
  { title: "Mthembu v Letsela", citation: "[2000] ZASCA 181", court: "Supreme Court of Appeal", year: 2000, tags: ["customary law","family law"], url: "https://www.saflii.org/za/cases/ZASCA/2000/181.html", summary: "Customary law of succession; extra-marital child's rights under customary law intestate succession." },
  { title: "Tongoane v National Minister for Agriculture", citation: "[2010] ZACC 10", court: "Constitutional Court", year: 2010, tags: ["customary law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2010/10.html", summary: "Communal Land Rights Act declared unconstitutional; required tagging as section 76 Bill for NCOP concurrence." },
  { title: "Rahube v Rahube", citation: "[2018] ZACC 42", court: "Constitutional Court", year: 2018, tags: ["customary law","property law"], url: "https://www.saflii.org/za/cases/ZACC/2018/42.html", summary: "Informal land rights; section 2(1) of Upgrading of Land Tenure Rights Act unconstitutional for gender discrimination." },

  // ── LAND REFORM / RESTITUTION ─────────────────────────────────────────
  { title: "Department of Land Affairs v Goedgelegen Tropical Fruits", citation: "[2007] ZACC 12", court: "Constitutional Court", year: 2007, tags: ["property law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2007/12.html", summary: "Labour tenant rights; broad interpretation of 'dispossession' under Restitution of Land Rights Act." },
  { title: "Popela Community v Goedgelegen Tropical Fruits", citation: "[2007] ZACC 12", court: "Constitutional Court", year: 2007, tags: ["property law"], url: "https://www.saflii.org/za/cases/ZACC/2007/12.html", summary: "Restitution of land rights; community dispossessed under racially discriminatory laws entitled to restoration." },
  { title: "Florence v Government of the RSA", citation: "[2014] ZACC 22", court: "Constitutional Court", year: 2014, tags: ["property law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2014/22.html", summary: "ESTA occupier rights; eviction from farm must comply with section 26(3) and provide alternative accommodation." },
  { title: "Daniels v Scribante", citation: "[2017] ZACC 13", court: "Constitutional Court", year: 2017, tags: ["property law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2017/13.html", summary: "ESTA occupier may make improvements to dwelling necessary for human dignity without owner's consent." },
  { title: "Baron v Claytile", citation: "[2017] ZACC 24", court: "Constitutional Court", year: 2017, tags: ["property law"], url: "https://www.saflii.org/za/cases/ZACC/2017/24.html", summary: "Section 26(3) eviction; former employee occupier cannot be evicted without court order." },

  // ── EDUCATION ─────────────────────────────────────────────────────────
  { title: "Governing Body of the Juma Musjid Primary School v Essay NO", citation: "[2011] ZACC 13", court: "Constitutional Court", year: 2011, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2011/13.html", summary: "Children's right to basic education; learners may not be evicted from school without alternative provision." },
  { title: "Head of Department: Mpumalanga v Hoërskool Ermelo", citation: "[2009] ZACC 32", court: "Constitutional Court", year: 2009, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/32.html", summary: "Language policy at public schools; MEC may withdraw function of school governing body that uses language to exclude." },
  { title: "MEC for Education v Pillay", citation: "[2007] ZACC 21", court: "Constitutional Court", year: 2007, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2007/21.html", summary: "School dress code and religious/cultural expression; nose stud as cultural practice entitled to exemption." },
  { title: "Federation of Governing Bodies v MEC for Education (Gauteng)", citation: "[2016] ZACC 14", court: "Constitutional Court", year: 2016, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2016/14.html", summary: "School admissions; Gauteng provincial school admission policy upheld against governing body autonomy challenge." },
  { title: "Minister of Education v Harris", citation: "[2001] ZACC 25", court: "Constitutional Court", year: 2001, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2001/25.html", summary: "Standard of matric examination; Minister's power to set curriculum standards for national examinations." },
  { title: "AB v Pridwin Preparatory School", citation: "[2020] ZACC 12", court: "Constitutional Court", year: 2020, tags: ["constitutional","contract law"], url: "https://www.saflii.org/za/cases/ZACC/2020/12.html", summary: "Private school cancellation of enrolment; horizontal application of Bill of Rights to independent schools." },

  // ── HEALTH ────────────────────────────────────────────────────────────
  { title: "Minister of Health v Treatment Action Campaign", citation: "[2002] ZACC 15", court: "Constitutional Court", year: 2002, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2002/15.html", summary: "Government must provide nevirapine to prevent mother-to-child HIV transmission; socio-economic rights enforceable." },
  { title: "Soobramoney v Minister of Health (KZN)", citation: "[1997] ZACC 17", court: "Constitutional Court", year: 1997, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1997/17.html", summary: "Right to emergency medical treatment; court defers to rational resource allocation decisions in healthcare." },
  { title: "Castell v De Greef", citation: "[1993] ZAWCHC 2", court: "Western Cape High Court", year: 1993, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZAWCHC/1993/2.html", summary: "Informed consent to medical treatment; patient autonomy requires disclosure of material risks." },
  { title: "Afrox Healthcare v Strydom", citation: "[2002] ZASCA 73", court: "Supreme Court of Appeal", year: 2002, tags: ["contract law","consumer"], url: "https://www.saflii.org/za/cases/ZASCA/2002/73.html", summary: "Exemption clause in hospital admission form; validity of clause excluding hospital's liability for negligence." },
  { title: "Michael v Linksfield Park Clinic", citation: "[2001] ZASCA 12", court: "Supreme Court of Appeal", year: 2001, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2001/12.html", summary: "Medical negligence; hospital vicariously liable for negligent acts of doctors working in its facilities." },

  // ── SOCIAL SECURITY / GRANTS ──────────────────────────────────────────
  { title: "Khosa v Minister of Social Development", citation: "[2004] ZACC 11", court: "Constitutional Court", year: 2004, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/11.html", summary: "Permanent residents entitled to social grants; exclusion of non-citizens from social assistance unconstitutional." },
  { title: "Mashavha v President of the RSA", citation: "[2004] ZACC 6", court: "Constitutional Court", year: 2004, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/6.html", summary: "Social grants administration; national and provincial government jointly responsible for social security delivery." },
  { title: "AllPay Consolidated Investment Holdings v CEO of SASSA", citation: "[2013] ZACC 42", court: "Constitutional Court", year: 2013, tags: ["constitutional","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2013/42.html", summary: "SASSA grants tender; procurement irregularities in social grants payment contract set aside." },
  { title: "AllPay Consolidated Investment Holdings v CEO of SASSA (No 2)", citation: "[2014] ZACC 12", court: "Constitutional Court", year: 2014, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2014/12.html", summary: "Remedy for invalid SASSA tender; suspended declaration of invalidity to ensure continued grant payments." },
  { title: "Black Sash Trust v Minister of Social Development", citation: "[2017] ZACC 8", court: "Constitutional Court", year: 2017, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2017/8.html", summary: "SASSA social grants crisis; court-supervised continuation of CPS contract to prevent disruption of grant payments." },
];
