// Environmental, Consumer, Competition, Mining, Media/POPIA, Immigration
module.exports = [
  // ── ENVIRONMENTAL ─────────────────────────────────────────────────────
  { title: "Fuel Retailers Association v DG: Environmental Management", citation: "[2007] ZACC 13", court: "Constitutional Court", year: 2007, tags: ["environmental","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2007/13.html", summary: "Environmental right under section 24; sustainable development integrates socio-economic and environmental protection." },
  { title: "MEC for Agriculture v HTF Developers", citation: "[2007] ZACC 25", court: "Constitutional Court", year: 2007, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZACC/2007/25.html", summary: "Heritage resources protection; environmental obligations apply even on private land with heritage significance." },
  { title: "BP Southern Africa v MEC for Agriculture (Gauteng)", citation: "[2004] ZASCA 64", court: "Supreme Court of Appeal", year: 2004, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZASCA/2004/64.html", summary: "NEMA duty of care; polluter-pays principle and liability for historical contamination of land." },
  { title: "Bengwenyama Minerals v Genorah Resources", citation: "[2010] ZACC 26", court: "Constitutional Court", year: 2010, tags: ["environmental","mining"], url: "https://www.saflii.org/za/cases/ZACC/2010/26.html", summary: "Community consultation before granting prospecting right; MPRDA requires meaningful engagement with affected communities." },
  { title: "Earthlife Africa Johannesburg v Minister of Energy", citation: "[2017] ZAGPPHC 58", court: "Gauteng High Court, Pretoria", year: 2017, tags: ["environmental","administrative"], url: "https://www.saflii.org/za/cases/ZAGPPHC/2017/58.html", summary: "Climate change considerations in environmental authorisation; nuclear procurement decision reviewed for rationality." },
  { title: "Trustees, Biowatch Trust v Registrar: Genetic Resources", citation: "[2009] ZACC 14", court: "Constitutional Court", year: 2009, tags: ["environmental","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/14.html", summary: "Cost orders in constitutional litigation; NGOs litigating in public interest should not bear adverse costs." },
  { title: "HTF Developers v Minister of Environmental Affairs", citation: "[2006] ZASCA 18", court: "Supreme Court of Appeal", year: 2006, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZASCA/2006/18.html", summary: "Environmental impact assessment requirements; developer must obtain authorisation before commencing listed activities." },
  { title: "Harmony Gold Mining v Regional Director: Free State", citation: "[2012] ZASCA 206", court: "Supreme Court of Appeal", year: 2012, tags: ["environmental","mining"], url: "https://www.saflii.org/za/cases/ZASCA/2012/206.html", summary: "Mine closure and environmental rehabilitation; ongoing obligation to rehabilitate even after cessation of mining." },
  { title: "Kloof Conservancy v Government of the RSA", citation: "[2015] ZAKZDHC 50", court: "KwaZulu-Natal High Court, Durban", year: 2015, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZAKZDHC/2015/50.html", summary: "NEMA section 28 duty of care; landowner liable for degradation caused by unlawful development on property." },
  { title: "Magaliesberg Protection Association v MEC Dept of Agriculture", citation: "[2013] ZAGPPHC 80", court: "Gauteng High Court, Pretoria", year: 2013, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZAGPPHC/2013/80.html", summary: "Heritage and environmental protection; development in sensitive mountain area requires proper EIA and heritage assessment." },

  // ── CONSUMER PROTECTION ───────────────────────────────────────────────
  { title: "Eskom Holdings v Halstead-Cleak", citation: "[2016] ZASCA 150", court: "Supreme Court of Appeal", year: 2016, tags: ["consumer","delict"], url: "https://www.saflii.org/za/cases/ZASCA/2016/150.html", summary: "Product liability under CPA section 61; strict liability for harm caused by defective goods or inadequate warnings." },
  { title: "Nedbank v Consumer Fair", citation: "[2013] ZAGPPHC 261", court: "Gauteng High Court, Pretoria", year: 2013, tags: ["consumer","banking"], url: "https://www.saflii.org/za/cases/ZAGPPHC/2013/261.html", summary: "Consumer's right to fair and honest dealing under CPA section 40; unconscionable conduct by suppliers." },
  { title: "Naidoo v Birchwood Hotel", citation: "[2012] ZAGPJHC 62", court: "Gauteng High Court, Johannesburg", year: 2012, tags: ["consumer"], url: "https://www.saflii.org/za/cases/ZAGPJHC/2012/62.html", summary: "Unfair contract terms under CPA section 48; supplier may not require consumer to waive rights." },
  { title: "Stellenbosch Wine Trust v Oude Nektar", citation: "[2019] ZASCA 75", court: "Supreme Court of Appeal", year: 2019, tags: ["consumer","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2019/75.html", summary: "Application of CPA to franchise agreements; franchisee as consumer entitled to CPA protections." },
  { title: "Auction Alliance v City of Cape Town", citation: "[2016] ZAWCHC 175", court: "Western Cape High Court", year: 2016, tags: ["consumer"], url: "https://www.saflii.org/za/cases/ZAWCHC/2016/175.html", summary: "Auctioneer obligations under CPA; disclosure requirements and prohibition of misleading marketing." },
  { title: "Ricardo v HPCSA", citation: "[2009] ZASCA 97", court: "Supreme Court of Appeal", year: 2009, tags: ["consumer"], url: "https://www.saflii.org/za/cases/ZASCA/2009/97.html", summary: "Professional services and consumer protection; medical practitioner's duty to inform patient of material risks." },

  // ── COMPETITION ───────────────────────────────────────────────────────
  { title: "Competition Commission v Pioneer Foods", citation: "[2010] ZACT 9", court: "Competition Tribunal", year: 2010, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACT/2010/9.html", summary: "Bread cartel; price-fixing as horizontal restrictive practice under Competition Act section 4(1)(b)." },
  { title: "Competition Commission v SAA", citation: "[2005] ZACT 50", court: "Competition Tribunal", year: 2005, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACT/2005/50.html", summary: "Abuse of dominance; predatory pricing and loyalty rebates to exclude competitors from market." },
  { title: "Sasol Chemical Industries v Competition Commission", citation: "[2015] ZACAC 4", court: "Competition Appeal Court", year: 2015, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACAC/2015/4.html", summary: "Excessive pricing under section 8(a); pricing above competitive level as abuse of dominance." },
  { title: "Mittal Steel SA v Harmony Gold Mining", citation: "[2009] ZACAC 1", court: "Competition Appeal Court", year: 2009, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACAC/2009/1.html", summary: "Excessive pricing test; comparing price to economic value and using multiple benchmarks." },
  { title: "Walmart v Competition Commission", citation: "[2011] ZACT 34", court: "Competition Tribunal", year: 2011, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACT/2011/34.html", summary: "Merger approval with conditions; Walmart acquisition of Massmart approved subject to employment and local procurement conditions." },
  { title: "Competition Commission v Yara SA", citation: "[2012] ZACT 84", court: "Competition Tribunal", year: 2012, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACT/2012/84.html", summary: "Market allocation cartel; territorial allocation of fertiliser markets as per se prohibition." },
  { title: "American Natural Soda Ash v Competition Commission", citation: "[2003] ZASCA 28", court: "Supreme Court of Appeal", year: 2003, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZASCA/2003/28.html", summary: "Locus standi in competition matters; foreign competitor may bring complaint under Competition Act." },

  // ── MINING / MINERALS ─────────────────────────────────────────────────
  { title: "Agri SA v Minister of Minerals and Energy", citation: "[2013] ZACC 9", court: "Constitutional Court", year: 2013, tags: ["mining","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2013/9.html", summary: "MPRDA mineral rights conversion not expropriation; custodianship model under new dispensation upheld." },
  { title: "Meepo v Kotze", citation: "[2008] ZASCA 56", court: "Supreme Court of Appeal", year: 2008, tags: ["mining","property law"], url: "https://www.saflii.org/za/cases/ZASCA/2008/56.html", summary: "Mineral rights vs surface rights; landowner and mineral right holder's competing interests." },
  { title: "Bengwenyama Minerals v Genorah Resources", citation: "[2010] ZACC 26", court: "Constitutional Court", year: 2010, tags: ["mining","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2010/26.html", summary: "Community consultation mandatory before prospecting rights granted; MPRDA requires meaningful community engagement." },
  { title: "Xstrata SA v SFF Association", citation: "[2012] ZASCA 134", court: "Supreme Court of Appeal", year: 2012, tags: ["mining"], url: "https://www.saflii.org/za/cases/ZASCA/2012/134.html", summary: "BEE requirements in mining; Mining Charter compliance and equity ownership requirements." },
  { title: "Minister of Mineral Resources v Sishen Iron Ore Co", citation: "[2013] ZACC 45", court: "Constitutional Court", year: 2013, tags: ["mining"], url: "https://www.saflii.org/za/cases/ZACC/2013/45.html", summary: "Allocation of prospecting rights; residual rights after MPRDA transitional period and competing applications." },

  // ── MEDIA / INFORMATION / POPIA ───────────────────────────────────────
  { title: "Khumalo v Holomisa", citation: "[2002] ZACC 12", court: "Constitutional Court", year: 2002, tags: ["constitutional","delict"], url: "https://www.saflii.org/za/cases/ZACC/2002/12.html", summary: "Defamation law and freedom of expression; media defendant's reasonable publication defence in public figure cases." },
  { title: "Midi Television v DPP (WC)", citation: "[2007] ZASCA 56", court: "Supreme Court of Appeal", year: 2007, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZASCA/2007/56.html", summary: "Open justice principle; media's right to broadcast court proceedings as aspect of freedom of expression." },
  { title: "Johncom Media v State", citation: "[2009] ZACC 5", court: "Constitutional Court", year: 2009, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/5.html", summary: "Publication ban on identity of accused; open justice and media freedom balanced against fair trial rights." },
  { title: "Brümmer v Minister for Social Development", citation: "[2009] ZACC 21", court: "Constitutional Court", year: 2009, tags: ["constitutional","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2009/21.html", summary: "PAIA right to access information; internal appeal requirement before court application for access." },
  { title: "President of the RSA v M&G Media", citation: "[2011] ZACC 32", court: "Constitutional Court", year: 2011, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2011/32.html", summary: "Access to records of disbanded Browse Mole report; transparency and accountability of executive." },
  { title: "Independent Newspapers v Minister for Intelligence Services", citation: "[2008] ZACC 6", court: "Constitutional Court", year: 2008, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2008/6.html", summary: "Access to intelligence records under PAIA; national security exemption must be narrowly construed." },
  { title: "Hyundai Motor Distributors v Smit NO", citation: "[2000] ZACC 12", court: "Constitutional Court", year: 2000, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2000/12.html", summary: "Investigation Directorate search warrants; section 14 privacy rights in electronic surveillance context." },

  // ── IMMIGRATION / CITIZENSHIP ─────────────────────────────────────────
  { title: "Union of Refugee Women v Director: Private Security Industry", citation: "[2006] ZACC 23", court: "Constitutional Court", year: 2006, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2006/23.html", summary: "Refugees' right to work; prohibition on refugees in security industry a justifiable limitation of right to choose occupation." },
  { title: "Lawyers for Human Rights v Minister of Home Affairs", citation: "[2004] ZACC 12", court: "Constitutional Court", year: 2004, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/12.html", summary: "Rights of illegal foreigners; everyone within South Africa entitled to basic constitutional protections regardless of immigration status." },
  { title: "Minister of Home Affairs v Watchenuka", citation: "[2003] ZASCA 142", court: "Supreme Court of Appeal", year: 2003, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZASCA/2003/142.html", summary: "Asylum seekers' right to work and study; blanket prohibition on employment pending asylum application unconstitutional." },
  { title: "Kaunda v President of the RSA", citation: "[2004] ZACC 5", court: "Constitutional Court", year: 2004, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/5.html", summary: "Diplomatic protection of citizens abroad; State has discretion but must consider request for assistance rationally." },
  { title: "Miriam v Minister of Home Affairs", citation: "[2014] ZAGPJHC 117", court: "Gauteng High Court, Johannesburg", year: 2014, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZAGPJHC/2014/117.html", summary: "Deportation of foreign national; procedural fairness and right to be heard before deportation order." },
  { title: "Scalabrini Centre v Minister of Home Affairs", citation: "[2013] ZAWCHC 49", court: "Western Cape High Court", year: 2013, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZAWCHC/2013/49.html", summary: "Closure of refugee reception office; refugees' right of access to asylum process cannot be frustrated by administrative decision." },
];
