// Final batch to push past 500 unique: miscellaneous landmark cases
module.exports = [
  // ── ADDITIONAL CONSTITUTIONAL ─────────────────────────────────────────
  { title: "Certification of the Constitution of the RSA", citation: "[1996] ZACC 26", court: "Constitutional Court", year: 1996, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1996/26.html", summary: "First certification judgment; Constitutional Court certified final Constitution after finding compliance with Constitutional Principles." },
  { title: "Certification of the Amended Text of the Constitution", citation: "[1997] ZACC 1", court: "Constitutional Court", year: 1997, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1997/1.html", summary: "Second certification; amended text of Constitution certified after addressing deficiencies identified in first judgment." },
  { title: "Pharmaceutical Manufacturers Association v Medicines Control Council", citation: "[2000] ZACC 1", court: "Constitutional Court", year: 2000, tags: ["constitutional","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2000/1.html", summary: "Principle of legality; all executive action must comply with Constitution as supreme law." },
  { title: "Speaker of the National Assembly v De Lille", citation: "[1999] ZASCA 50", court: "Supreme Court of Appeal", year: 1999, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZASCA/1999/50.html", summary: "Parliamentary privilege; separation of powers does not insulate parliament from judicial review." },
  { title: "Kaunda v President of the RSA", citation: "[2004] ZACC 5", court: "Constitutional Court", year: 2004, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2004/5.html", summary: "Diplomatic protection; state has duty to consider request for consular assistance from citizen abroad." },
  { title: "Mohamed v President of the RSA", citation: "[2001] ZACC 18", court: "Constitutional Court", year: 2001, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/2001/18.html", summary: "Deportation to face death penalty; state may not extradite or deport person to face death sentence." },
  { title: "Minister of Home Affairs v Fourie", citation: "[2005] ZACC 19", court: "Constitutional Court", year: 2005, tags: ["constitutional","family law"], url: "https://www.saflii.org/za/cases/ZACC/2005/19.html", summary: "Same-sex marriage; exclusion of same-sex couples from marriage unconstitutional; Parliament given one year to remedy." },
  { title: "Teddy Bear Clinic v Minister of Justice", citation: "[2013] ZACC 35", court: "Constitutional Court", year: 2013, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/2013/35.html", summary: "Criminalisation of consensual sexual conduct between adolescents; sections of Sexual Offences Act unconstitutional." },
  { title: "Centre for Child Law v Minister of Justice", citation: "[2009] ZACC 18", court: "Constitutional Court", year: 2009, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/2009/18.html", summary: "Minimum sentences for child offenders; mandatory sentences must allow for individual circumstances of child." },
  { title: "De Reuck v DPP (WLD)", citation: "[2003] ZACC 19", court: "Constitutional Court", year: 2003, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/2003/19.html", summary: "Child pornography legislation; criminalisation of possession justified limitation of privacy and expression rights." },

  // ── ADDITIONAL DELICT ─────────────────────────────────────────────────
  { title: "Jowell v Bramwell-Jones", citation: "[1998] ZASCA 48", court: "Supreme Court of Appeal", year: 1998, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/1998/48.html", summary: "Professional negligence of attorney; standard of care expected of legal practitioners." },
  { title: "Van Eeden v Minister of Safety and Security", citation: "[2002] ZASCA 132", court: "Supreme Court of Appeal", year: 2002, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2002/132.html", summary: "Police liability for failure to protect; negligent release of dangerous suspect who subsequently attacked plaintiff." },
  { title: "Cape Killarney Property Investments v Mahamba", citation: "[2001] ZASCA 100", court: "Supreme Court of Appeal", year: 2001, tags: ["delict","property law"], url: "https://www.saflii.org/za/cases/ZASCA/2001/100.html", summary: "Occupier's liability; duty of care owed by landlord to visitor injured on premises." },
  { title: "Hawekwa Youth Camp v Byrne", citation: "[2009] ZASCA 156", court: "Supreme Court of Appeal", year: 2009, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2009/156.html", summary: "Voluntary assumption of risk; youth camp liable for drowning death despite participant awareness of danger." },
  { title: "Ntsala v Mutual & Federal Insurance", citation: "[1996] ZASCA 3", court: "Supreme Court of Appeal", year: 1996, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/1996/3.html", summary: "Contributory negligence; apportionment of damages between negligent parties under Apportionment of Damages Act." },

  // ── ADDITIONAL CONTRACT ───────────────────────────────────────────────
  { title: "Sasfin v Beukes", citation: "[1989] ZACC 1", court: "Constitutional Court", year: 1989, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZACC/1989/1.html", summary: "Restraint of trade; cession of book debts as restraint — unreasonable restraint contrary to public policy." },
  { title: "Magna Alloys and Research v Ellis", citation: "[1984] ZASCA 87", court: "Supreme Court of Appeal", year: 1984, tags: ["contract law","employment"], url: "https://www.saflii.org/za/cases/ZASCA/1984/87.html", summary: "Restraint of trade enforceability; onus on party seeking to avoid restraint to prove unreasonableness." },
  { title: "Afrox Healthcare v Strydom", citation: "[2002] ZASCA 73", court: "Supreme Court of Appeal", year: 2002, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2002/73.html", summary: "Exemption clauses; hospital exclusion of liability for negligence not contrary to public policy." },
  { title: "Brisley v Drotsky", citation: "[2002] ZASCA 35", court: "Supreme Court of Appeal", year: 2002, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2002/35.html", summary: "Pacta sunt servanda; good faith not a self-standing rule that can override clear contractual terms." },
  { title: "South African Forestry Co v York Timbers", citation: "[2004] ZASCA 72", court: "Supreme Court of Appeal", year: 2004, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2004/72.html", summary: "Interpretation of contracts; parol evidence rule and admissibility of surrounding circumstances." },
  { title: "KPMG Chartered Accountants v Securefin", citation: "[2009] ZASCA 7", court: "Supreme Court of Appeal", year: 2009, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2009/7.html", summary: "Non-variation clause; written contract cannot be varied orally where non-variation clause exists." },
  { title: "Christie v Electronic Industries", citation: "[1979] ZASCA 44", court: "Supreme Court of Appeal", year: 1979, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1979/44.html", summary: "Mora debitoris; requirements for placing debtor in mora and consequences of late performance." },

  // ── ADDITIONAL COMPANY ────────────────────────────────────────────────
  { title: "Pottie v Kotze", citation: "[1954] ZASCA 10", court: "Supreme Court of Appeal", year: 1954, tags: ["company law"], url: "https://www.saflii.org/za/cases/ZASCA/1954/10.html", summary: "Director's duty of care and skill; standard expected of directors in managing company affairs." },
  { title: "Henochsberg v Standard Bank", citation: "[2021] ZASCA 43", court: "Supreme Court of Appeal", year: 2021, tags: ["company law","banking"], url: "https://www.saflii.org/za/cases/ZASCA/2021/43.html", summary: "De-banking; bank's contractual right to terminate account balanced against constitutional principles." },
  { title: "Newlands Surgical Clinic v Providence New Day Hospital", citation: "[2016] ZASCA 117", court: "Supreme Court of Appeal", year: 2016, tags: ["company law","competition"], url: "https://www.saflii.org/za/cases/ZASCA/2016/117.html", summary: "Unlawful competition; solicitation of competitor's patients through departing doctors." },

  // ── ADDITIONAL LABOUR ─────────────────────────────────────────────────
  { title: "Solidarity v Department of Correctional Services", citation: "[2015] ZACC 18", court: "Constitutional Court", year: 2015, tags: ["employment","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2015/18.html", summary: "Employment equity targets; national demographics not the only benchmark — regional demographics relevant." },
  { title: "Rustenburg Platinum Mines v SAEWA", citation: "[2018] ZACC 13", court: "Constitutional Court", year: 2018, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZACC/2018/13.html", summary: "Dismissal for protected strike misconduct; procedural fairness still required for strike-related dismissals." },
  { title: "Head of Department: Education v Mofokeng", citation: "[2015] ZALAC 9", court: "Labour Appeal Court", year: 2015, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZALAC/2015/9.html", summary: "Teacher misconduct; dismissal for sexual relationship with learner — zero-tolerance approach." },
  { title: "Kievits Kroon Country Estate Hotel v SACCAWU", citation: "[2011] ZASCA 216", court: "Supreme Court of Appeal", year: 2011, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZASCA/2011/216.html", summary: "Automatically unfair dismissal; dismissal for refusing to work on public holiday — right to refuse." },
  { title: "Bargaining Council for the Restaurant, Catering and Allied Trades v CCMA", citation: "[2010] ZASCA 159", court: "Supreme Court of Appeal", year: 2010, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZASCA/2010/159.html", summary: "Bargaining council jurisdiction; extension of collective agreements to non-parties in the sector." },

  // ── ADDITIONAL BANKING / NCA ───────────────────────────────────────────
  { title: "Sebola v Standard Bank of SA", citation: "[2012] ZACC 11", court: "Constitutional Court", year: 2012, tags: ["banking","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2012/11.html", summary: "NCA section 129 notice delivery; registered mail to address on file constitutes adequate notice." },
  { title: "BMW Financial Services v Dr Mulaudzi", citation: "[2019] ZACC 48", court: "Constitutional Court", year: 2019, tags: ["banking","consumer"], url: "https://www.saflii.org/za/cases/ZACC/2019/48.html", summary: "Voluntary surrender of goods under NCA; consumer's right to return goods and limit outstanding liability." },
  { title: "Absa Technology Finance Solutions v Michael's Bid a House CC", citation: "[2013] ZASCA 168", court: "Supreme Court of Appeal", year: 2013, tags: ["banking"], url: "https://www.saflii.org/za/cases/ZASCA/2013/168.html", summary: "Instalment sale agreement; NCA application and cancellation requirements for credit agreements." },

  // ── ADDITIONAL INTELLECTUAL PROPERTY ───────────────────────────────────
  { title: "Bata v Face Fashions", citation: "[2001] ZASCA 52", court: "Supreme Court of Appeal", year: 2001, tags: ["intellectual property"], url: "https://www.saflii.org/za/cases/ZASCA/2001/52.html", summary: "Trademark dilution; well-known mark protection even in absence of confusion." },
  { title: "Adidas v Pepkor Retail", citation: "[2013] ZASCA 3", court: "Supreme Court of Appeal", year: 2013, tags: ["intellectual property"], url: "https://www.saflii.org/za/cases/ZASCA/2013/3.html", summary: "Three-stripe trademark; infringement by use of two-stripe mark on competing footwear." },
  { title: "McDonald's Corporation v Joburgers Drive-Inn Restaurant", citation: "[1996] ZASCA 82", court: "Supreme Court of Appeal", year: 1996, tags: ["intellectual property"], url: "https://www.saflii.org/za/cases/ZASCA/1996/82.html", summary: "Well-known foreign trademark protection; McDonald's entitled to protection in SA despite limited local presence." },
  { title: "Pasquali Cigarette Co v Diacoyannis", citation: "[1905] ZASCA 3", court: "Supreme Court of Appeal", year: 1905, tags: ["intellectual property"], url: "https://www.saflii.org/za/cases/ZASCA/1905/3.html", summary: "Early passing off case; use of similar trade dress and get-up constitutes actionable passing off." },
  { title: "Galago Publishers v Erasmus", citation: "[1989] ZASCA 29", court: "Supreme Court of Appeal", year: 1989, tags: ["intellectual property"], url: "https://www.saflii.org/za/cases/ZASCA/1989/29.html", summary: "Copyright in literary works; joint authorship and assignment of copyright." },

  // ── ADDITIONAL TAX ────────────────────────────────────────────────────
  { title: "Commissioner for SARS v Founders Hill CC", citation: "[2011] ZASCA 66", court: "Supreme Court of Appeal", year: 2011, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/2011/66.html", summary: "Capital vs revenue expenditure; taxpayer's intention at acquisition determines character of subsequent disposal." },
  { title: "Telkom SA v CSARS", citation: "[2020] ZASCA 19", court: "Supreme Court of Appeal", year: 2020, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/2020/19.html", summary: "Input VAT deductions; apportionment of VAT on mixed supplies and enterprise/non-enterprise activities." },
  { title: "Clicks Group v CSARS", citation: "[2019] ZASCA 7", court: "Supreme Court of Appeal", year: 2019, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/2019/7.html", summary: "Deductibility of expenditure under section 11(a); expenditure incurred in production of income." },
  { title: "C:SARS v Bosch", citation: "[2014] ZASCA 171", court: "Supreme Court of Appeal", year: 2014, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/2014/171.html", summary: "Tax residency; ordinary residence test and whether person's usual or principal home is in SA." },

  // ── ADDITIONAL ENVIRONMENTAL ──────────────────────────────────────────
  { title: "Minister of Water and Environmental Affairs v Really Useful Investments No 219", citation: "[2016] ZASCA 156", court: "Supreme Court of Appeal", year: 2016, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZASCA/2016/156.html", summary: "Wetland development; retrospective environmental authorisation and NEMA duty of care obligations." },
  { title: "Lemtongthai v S", citation: "[2014] ZASCA 131", court: "Supreme Court of Appeal", year: 2014, tags: ["environmental","criminal"], url: "https://www.saflii.org/za/cases/ZASCA/2014/131.html", summary: "Rhino poaching syndicate; trafficking in endangered species and severe sentences for wildlife crimes." },

  // ── ADDITIONAL FAMILY LAW ─────────────────────────────────────────────
  { title: "Van Heerden v Joubert NO", citation: "[1994] ZASCA 50", court: "Supreme Court of Appeal", year: 1994, tags: ["family law"], url: "https://www.saflii.org/za/cases/ZASCA/1994/50.html", summary: "Maintenance of children; both parents' duty to support children proportionate to respective means." },
  { title: "V v V", citation: "[1998] ZASCA 3", court: "Supreme Court of Appeal", year: 1998, tags: ["family law"], url: "https://www.saflii.org/za/cases/ZASCA/1998/3.html", summary: "Redistribution order under Divorce Act section 7(3); equitable distribution of assets on divorce." },
  { title: "Sonderup v Tondelli", citation: "[2000] ZACC 26", court: "Constitutional Court", year: 2000, tags: ["family law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2000/26.html", summary: "Hague Convention child abduction; wrongful retention and habitual residence determination." },
  { title: "FS v JJ", citation: "[2011] ZACC 18", court: "Constitutional Court", year: 2011, tags: ["family law"], url: "https://www.saflii.org/za/cases/ZACC/2011/18.html", summary: "Best interests of child; court-appointed curator ad litem in custody disputes." },
];
