// Additional cases across all areas to reach ~500
module.exports = [
  // ── More Constitutional ───────────────────────────────────────────────
  { title: "Affordable Medicines Trust v Minister of Health", citation: "[2005] ZACC 3", court: "Constitutional Court", year: 2005, tags: ["constitutional","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2005/3.html", summary: "Licensing of pharmacies; limitation on freedom of trade must be rationally connected to legitimate government purpose." },
  { title: "S v Bhulwana; S v Gwadiso", citation: "[1995] ZACC 11", court: "Constitutional Court", year: 1995, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/1995/11.html", summary: "Reverse onus for dealing in drugs; presumption arising from possession of quantity violates presumption of innocence." },
  { title: "Ex parte Minister of Safety and Security: In Re S v Walters", citation: "[2002] ZACC 6", court: "Constitutional Court", year: 2002, tags: ["constitutional","criminal"], url: "https://www.saflii.org/za/cases/ZACC/2002/6.html", summary: "Use of lethal force by police to effect arrest; section 49 of Criminal Procedure Act must comply with right to life." },
  { title: "Rail Commuters Action Group v Transnet", citation: "[2004] ZACC 20", court: "Constitutional Court", year: 2004, tags: ["constitutional","delict"], url: "https://www.saflii.org/za/cases/ZACC/2004/20.html", summary: "Positive duty on state and Transnet to protect commuters; constitutional obligation to ensure passenger safety." },
  { title: "Occupiers of 51 Olivia Road v City of Johannesburg", citation: "[2008] ZACC 1", court: "Constitutional Court", year: 2008, tags: ["constitutional","property law"], url: "https://www.saflii.org/za/cases/ZACC/2008/1.html", summary: "Meaningful engagement required before eviction of unlawful occupiers; municipality must engage in good faith." },
  { title: "Residents of Joe Slovo v Thubelisha Homes", citation: "[2009] ZACC 16", court: "Constitutional Court", year: 2009, tags: ["constitutional","property law"], url: "https://www.saflii.org/za/cases/ZACC/2009/16.html", summary: "N2 Gateway housing project eviction; relocation must be to adequate alternative accommodation." },
  { title: "Modderklip Boerdery v Modder East Squatters", citation: "[2004] ZASCA 47", court: "Supreme Court of Appeal", year: 2004, tags: ["constitutional","property law"], url: "https://www.saflii.org/za/cases/ZASCA/2004/47.html", summary: "State's duty to provide alternative land when large-scale eviction impractical; constitutional damages awarded." },
  { title: "Lindiwe Mazibuko v City of Johannesburg", citation: "[2009] ZACC 28", court: "Constitutional Court", year: 2009, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/28.html", summary: "Pre-paid water meters in Soweto; courts should be slow to prescribe to government what constitutes sufficient water." },
  { title: "Helen Suzman Foundation v President of the RSA", citation: "[2014] ZACC 32", court: "Constitutional Court", year: 2014, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2014/32.html", summary: "Appointment of NDPP; rationality review of executive appointments to key constitutional positions." },
  { title: "Speaker of the National Assembly v De Lille", citation: "[1999] ZASCA 50", court: "Supreme Court of Appeal", year: 1999, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZASCA/1999/50.html", summary: "Parliamentary privilege; courts have jurisdiction to review exercise of powers by National Assembly." },
  { title: "Oriani-Ambrosini v Sisulu", citation: "[2012] ZACC 27", court: "Constitutional Court", year: 2012, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2012/27.html", summary: "Individual MP's right to introduce legislation; section 73(2) does not limit right to Cabinet members." },
  { title: "Mazibuko v Sisulu", citation: "[2013] ZACC 28", court: "Constitutional Court", year: 2013, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2013/28.html", summary: "Motion of no confidence in President; secret ballot not constitutionally required but Speaker has discretion." },
  { title: "United Democratic Movement v Speaker", citation: "[2017] ZACC 21", court: "Constitutional Court", year: 2017, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2017/21.html", summary: "Secret ballot in motion of no confidence; Speaker must prescribe voting procedure ensuring free exercise of conscience." },
  { title: "Masethla v President of the RSA", citation: "[2007] ZACC 20", court: "Constitutional Court", year: 2007, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2007/20.html", summary: "President's power to appoint and dismiss DG of NIA; rationality review of executive dismissal decisions." },

  // ── More Contract / Commercial ────────────────────────────────────────
  { title: "Beadica 231 CC v Trustees, Oregon Trust", citation: "[2020] ZACC 13", court: "Constitutional Court", year: 2020, tags: ["contract law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2020/13.html", summary: "Contractual freedom and fairness; time-bar clauses enforced — good faith does not override clear contractual terms." },
  { title: "AB Ventures v Siemens", citation: "[2011] ZASCA 48", court: "Supreme Court of Appeal", year: 2011, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2011/48.html", summary: "Tender process and contractual obligations arising from invitation to tender; binding effect of procurement rules." },
  { title: "Rapp v Van Deventer", citation: "[2019] ZASCA 105", court: "Supreme Court of Appeal", year: 2019, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2019/105.html", summary: "Cession of rights; requirements for valid cession and effect on underlying obligation." },
  { title: "Trustees, Two Oceans Aquarium Trust v Kantey & Templer", citation: "[2006] ZASCA 109", court: "Supreme Court of Appeal", year: 2006, tags: ["delict","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2006/109.html", summary: "Professional negligence of engineers; pure economic loss from defective design work." },
  { title: "Standard Bank v Oneanate Investments", citation: "[1998] ZASCA 2", court: "Supreme Court of Appeal", year: 1998, tags: ["banking","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1998/2.html", summary: "Enrichment claim; condictio indebiti for recovery of payment made in error by bank." },
  { title: "Kudu Granite Operations v Caterna", citation: "[2003] ZASCA 59", court: "Supreme Court of Appeal", year: 2003, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2003/59.html", summary: "Supervening impossibility of performance; contract extinguished when performance becomes objectively impossible." },
  { title: "Murray & Roberts v Fifita Construction", citation: "[2007] ZASCA 123", court: "Supreme Court of Appeal", year: 2007, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2007/123.html", summary: "Building contract disputes; interpretation of JBCC and FIDIC standard form construction contracts." },
  { title: "Absa Bank v Moore", citation: "[2016] ZASCA 137", court: "Supreme Court of Appeal", year: 2016, tags: ["banking","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2016/137.html", summary: "Bank's duty of care to customer; negligent processing of payment instruction and estoppel." },

  // ── More Delict ───────────────────────────────────────────────────────
  { title: "Loureiro v iMvula Quality Protection", citation: "[2014] ZACC 4", court: "Constitutional Court", year: 2014, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZACC/2014/4.html", summary: "Vicarious liability of security company; employer liable for employee's intentional shooting during course of employment." },
  { title: "K v Minister of Safety and Security", citation: "[2005] ZACC 8", court: "Constitutional Court", year: 2005, tags: ["delict","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2005/8.html", summary: "Vicarious liability for rape by off-duty police officers; State liable where employment created risk of harm." },
  { title: "F v Minister of Safety and Security", citation: "[2011] ZACC 37", court: "Constitutional Court", year: 2011, tags: ["delict","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2011/37.html", summary: "Police rape of minor; sufficiently close link between employment and wrong for vicarious liability." },
  { title: "Minister of Safety and Security v F", citation: "[2011] ZACC 37", court: "Constitutional Court", year: 2011, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZACC/2011/37.html", summary: "Extended test for vicarious liability of State for police officers' sexual violence." },
  { title: "Telematrix v Advertising Standards Authority", citation: "[2005] ZASCA 73", court: "Supreme Court of Appeal", year: 2005, tags: ["delict","administrative"], url: "https://www.saflii.org/za/cases/ZASCA/2005/73.html", summary: "Wrongful interference with trade; ASA ruling causing advertiser to lose business constitutes actionable wrong." },
  { title: "Media 24 Ltd v SA Taxi Securitisation", citation: "[2011] ZASCA 117", court: "Supreme Court of Appeal", year: 2011, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2011/117.html", summary: "Media defamation; reasonable publication defence and requirements for responsible journalism." },
  { title: "Piliso v Old Mutual Life", citation: "[2007] ZASCA 30", court: "Supreme Court of Appeal", year: 2007, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2007/30.html", summary: "Emotional shock; psychological injury from witnessing death of close relative in accident." },
  { title: "MTO Forestry v Swart", citation: "[2017] ZASCA 35", court: "Supreme Court of Appeal", year: 2017, tags: ["delict","environmental"], url: "https://www.saflii.org/za/cases/ZASCA/2017/35.html", summary: "Runaway fire liability; landowner's duty of care to prevent fire from spreading to neighbouring properties." },

  // ── More Labour ───────────────────────────────────────────────────────
  { title: "National Education Health & Allied Workers Union v University of Cape Town", citation: "[2002] ZACC 27", court: "Constitutional Court", year: 2002, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZACC/2002/27.html", summary: "Outsourcing; section 197 transfer of undertaking when university outsources catering and cleaning services." },
  { title: "CWIU v Algorax", citation: "[2003] ZASCA 158", court: "Supreme Court of Appeal", year: 2003, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZASCA/2003/158.html", summary: "Reinstatement as primary remedy for unfair dismissal; compensation only where reinstatement impracticable." },
  { title: "Numsa v Dunlop Mixing & Technical", citation: "[2019] ZACC 25", court: "Constitutional Court", year: 2019, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZACC/2019/25.html", summary: "Picketing rules; interdict against striking employees blocking access; balance of rights during industrial action." },
  { title: "South African Revenue Service v Commission for Conciliation", citation: "[2016] ZACC 38", court: "Constitutional Court", year: 2016, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZACC/2016/38.html", summary: "Protected disclosure (whistle-blowing) under Protected Disclosures Act; occupational detriment for making disclosure." },
  { title: "CUSA v Tao Ying Metal Industries", citation: "[2008] ZACC 15", court: "Constitutional Court", year: 2008, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZACC/2008/15.html", summary: "CCMA jurisdiction over unfair dismissal; employee's right to legal representation at CCMA." },
  { title: "Tikly v Johannes NO", citation: "[1963] ZASCA 4", court: "Supreme Court of Appeal", year: 1963, tags: ["employment","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1963/4.html", summary: "Employment relationship; implied duties of employer including duty to provide safe workplace." },
  { title: "Brassey v Bosal Africa", citation: "[1984] ZASCA 61", court: "Supreme Court of Appeal", year: 1984, tags: ["employment"], url: "https://www.saflii.org/za/cases/ZASCA/1984/61.html", summary: "Employment contract terms; employer's right to instruct employee within scope of employment agreement." },

  // ── More Property ─────────────────────────────────────────────────────
  { title: "City of Johannesburg v Changing Tides 74", citation: "[2012] ZASCA 116", court: "Supreme Court of Appeal", year: 2012, tags: ["property law"], url: "https://www.saflii.org/za/cases/ZASCA/2012/116.html", summary: "Building regulations and property rights; unauthorised building work and demolition orders." },
  { title: "Bartlett v Hayma Investments", citation: "[2016] ZASCA 192", court: "Supreme Court of Appeal", year: 2016, tags: ["property law"], url: "https://www.saflii.org/za/cases/ZASCA/2016/192.html", summary: "Prescription of immovable property; acquisitive prescription requirements under Prescription Act." },
  { title: "Camps Bay Ratepayers v Harrison", citation: "[2010] ZACC 19", court: "Constitutional Court", year: 2010, tags: ["property law","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2010/19.html", summary: "Spatial planning and zoning; neighbours' rights to be heard before building plan approvals." },
  { title: "Shoprite Checkers v MEC for Economic Development (EP)", citation: "[2015] ZACC 23", court: "Constitutional Court", year: 2015, tags: ["property law","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2015/23.html", summary: "Liquor licence and property rights; administrative decision affecting property must comply with PAJA." },
  { title: "Steinberg v South Peninsula Municipality", citation: "[2001] ZASCA 21", court: "Supreme Court of Appeal", year: 2001, tags: ["property law"], url: "https://www.saflii.org/za/cases/ZASCA/2001/21.html", summary: "Municipal planning law; rezoning refusal must be rational and based on legitimate planning considerations." },

  // ── More Family ───────────────────────────────────────────────────────
  { title: "Dawood v Minister of Home Affairs", citation: "[2000] ZACC 8", court: "Constitutional Court", year: 2000, tags: ["family law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2000/8.html", summary: "Right to family life; immigration provisions restricting foreign spouses from applying for permits struck down." },
  { title: "Du Toit v Minister of Welfare and Population Development", citation: "[2002] ZACC 20", court: "Constitutional Court", year: 2002, tags: ["family law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2002/20.html", summary: "Same-sex couples' right to adopt children jointly; Child Care Act provisions extended to life partners." },
  { title: "J v Director General: Department of Home Affairs", citation: "[2003] ZACC 3", court: "Constitutional Court", year: 2003, tags: ["family law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2003/3.html", summary: "Same-sex couple's right to be registered as parents of children born through artificial insemination." },
  { title: "Centre for Child Law v Hoërskool Fochville", citation: "[2016] ZASCA 155", court: "Supreme Court of Appeal", year: 2016, tags: ["family law"], url: "https://www.saflii.org/za/cases/ZASCA/2016/155.html", summary: "Children's right to education and language; school may not use language policy to exclude learners." },
  { title: "Government of the RSA v Figg", citation: "[2014] ZASCA 95", court: "Supreme Court of Appeal", year: 2014, tags: ["family law"], url: "https://www.saflii.org/za/cases/ZASCA/2014/95.html", summary: "International child abduction; Hague Convention return order and defences under Article 13." },

  // ── More Tax ──────────────────────────────────────────────────────────
  { title: "Commissioner for SARS v Yulana CC", citation: "[2012] ZASCA 184", court: "Supreme Court of Appeal", year: 2012, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/2012/184.html", summary: "Tax avoidance schemes; court looks at substance over form to determine true nature of transaction." },
  { title: "Natal Estates v SIR", citation: "[1975] ZASCA 3", court: "Supreme Court of Appeal", year: 1975, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/1975/3.html", summary: "Income vs capital receipts; intention of taxpayer at time of acquisition determines character of receipt." },
  { title: "Lategan v CIR", citation: "[1926] ZASCA 4", court: "Supreme Court of Appeal", year: 1926, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/1926/4.html", summary: "Definition of gross income; 'amount received' includes every form of property with ascertainable money value." },
  { title: "WH Lategan v CIR", citation: "[1926] ZASCA 4", court: "Supreme Court of Appeal", year: 1926, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/1926/4.html", summary: "Wide interpretation of 'gross income'; value of right to receive wheat crop constitutes taxable receipt." },
  { title: "CSARS v Executor, Estate Frith", citation: "[2001] ZASCA 37", court: "Supreme Court of Appeal", year: 2001, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/2001/37.html", summary: "Estate duty; deemed property and the valuation of assets passing on death for estate duty purposes." },
  { title: "Stellenbosch Farmers' Winery v CSARS", citation: "[2012] ZASCA 72", court: "Supreme Court of Appeal", year: 2012, tags: ["tax"], url: "https://www.saflii.org/za/cases/ZASCA/2012/72.html", summary: "Customs and excise; classification of goods for duty purposes and tariff interpretation." },

  // ── More Insolvency ───────────────────────────────────────────────────
  { title: "Stratford v Investec Bank", citation: "[2014] ZACC 38", court: "Constitutional Court", year: 2014, tags: ["insolvency","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2014/38.html", summary: "Provisional sequestration; nulla bona return as prima facie evidence of insolvency." },
  { title: "FirstRand Bank v Evans", citation: "[2011] ZASCA 36", court: "Supreme Court of Appeal", year: 2011, tags: ["insolvency","banking"], url: "https://www.saflii.org/za/cases/ZASCA/2011/36.html", summary: "Compulsory sequestration vs debt review; NCA debt review does not prevent sequestration proceedings." },
  { title: "Nedbank v Bestvest", citation: "[2012] ZASCA 103", court: "Supreme Court of Appeal", year: 2012, tags: ["insolvency"], url: "https://www.saflii.org/za/cases/ZASCA/2012/103.html", summary: "Business rescue vs liquidation; when business rescue application is an abuse of process to delay liquidation." },

  // ── More Competition ──────────────────────────────────────────────────
  { title: "Competition Commission v Telkom SA", citation: "[2010] ZACT 58", court: "Competition Tribunal", year: 2010, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACT/2010/58.html", summary: "Refusal to deal and margin squeeze; Telkom's abuse of dominance in telecommunications market." },
  { title: "Mediclinic v Competition Commission", citation: "[2018] ZACAC 3", court: "Competition Appeal Court", year: 2018, tags: ["competition"], url: "https://www.saflii.org/za/cases/ZACAC/2018/3.html", summary: "Hospital merger conditions; public interest considerations in healthcare sector mergers." },

  // ── More Mining ───────────────────────────────────────────────────────
  { title: "Joubert v Maranda Mining Company", citation: "[2009] ZASCA 44", court: "Supreme Court of Appeal", year: 2009, tags: ["mining","property law"], url: "https://www.saflii.org/za/cases/ZASCA/2009/44.html", summary: "Legal professional privilege in mining context; documents prepared for litigation privileged." },
  { title: "Maledu v Itereleng Bakgatla Mineral Resources", citation: "[2018] ZACC 41", court: "Constitutional Court", year: 2018, tags: ["mining","constitutional","property law"], url: "https://www.saflii.org/za/cases/ZACC/2018/41.html", summary: "Community mining rights; MPRDA does not override community's right to occupy and use ancestral land." },

  // ── More Media / Information ──────────────────────────────────────────
  { title: "Tshabalala-Msimang v Makhanya", citation: "[2008] ZASCA 51", court: "Supreme Court of Appeal", year: 2008, tags: ["constitutional","delict"], url: "https://www.saflii.org/za/cases/ZASCA/2008/51.html", summary: "Media publication of minister's medical records; privacy rights vs public interest and freedom of expression." },
  { title: "Le Roux v Dey", citation: "[2011] ZACC 4", court: "Constitutional Court", year: 2011, tags: ["delict","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2011/4.html", summary: "Defamation by schoolboys creating manipulated image of teacher; requirements for defamation in digital age." },
  { title: "NM v Smith (Freedom of Expression Institute as Amicus Curiae)", citation: "[2007] ZACC 6", court: "Constitutional Court", year: 2007, tags: ["constitutional","delict"], url: "https://www.saflii.org/za/cases/ZACC/2007/6.html", summary: "Disclosure of HIV status; privacy rights override public interest in unauthorized revelation of medical information." },

  // ── More Immigration ──────────────────────────────────────────────────
  { title: "Somali Association of SA v Limpopo Dept of Economic Development", citation: "[2014] ZASCA 143", court: "Supreme Court of Appeal", year: 2014, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZASCA/2014/143.html", summary: "Foreign national traders; unlawful closure of Somali-owned businesses by municipality set aside." },
  { title: "Ruta v Minister of Home Affairs", citation: "[2018] ZACC 52", court: "Constitutional Court", year: 2018, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2018/52.html", summary: "Asylum seekers may apply for refugee status at any reception office; geographical restriction unconstitutional." },

  // ── More Environmental ────────────────────────────────────────────────
  { title: "Minister of Water Affairs v Stilfontein Gold Mining", citation: "[2006] ZAGPPHC 47", court: "Gauteng High Court, Pretoria", year: 2006, tags: ["environmental","mining"], url: "https://www.saflii.org/za/cases/ZAGPPHC/2006/47.html", summary: "Acid mine drainage; mine's ongoing duty to treat polluted water even after cessation of mining operations." },
  { title: "Bareki v Gencor Industries", citation: "[2006] ZASCA 28", court: "Supreme Court of Appeal", year: 2006, tags: ["environmental","delict"], url: "https://www.saflii.org/za/cases/ZASCA/2006/28.html", summary: "Asbestos pollution; class action for environmental harm and long-latency disease caused by mining." },
  { title: "Company Secretary of ArcelorMittal v Vaal Environmental Justice Alliance", citation: "[2014] ZASCA 184", court: "Supreme Court of Appeal", year: 2014, tags: ["environmental"], url: "https://www.saflii.org/za/cases/ZASCA/2014/184.html", summary: "PAIA access to environmental compliance records; community right to know about pollution risks." },

  // ── More Consumer ─────────────────────────────────────────────────────
  { title: "Arrowsmith v Arrowsmith", citation: "[2019] ZASCA 122", court: "Supreme Court of Appeal", year: 2019, tags: ["consumer","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2019/122.html", summary: "CPA application to property transactions; whether sale of immovable property between individuals falls under CPA." },
  { title: "Mercurius Motors v Lopez", citation: "[2008] ZASCA 104", court: "Supreme Court of Appeal", year: 2008, tags: ["consumer","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2008/104.html", summary: "Voetstoots clause and latent defects in sale of motor vehicle; seller's knowledge and consumer rights." },
  { title: "Standard Bank v Hunkydory Investments", citation: "[2010] ZASCA 47", court: "Supreme Court of Appeal", year: 2010, tags: ["consumer","banking"], url: "https://www.saflii.org/za/cases/ZASCA/2010/47.html", summary: "NCA reckless lending; credit provider's obligation to conduct proper affordability assessment before granting credit." },
];
