// More cases: Arbitration, Suretyship, Insurance, Trusts, Wills, Marine, Aviation, Sport
module.exports = [
  // ── ARBITRATION / ADR ─────────────────────────────────────────────────
  { title: "Lufuno Mphaphuli & Associates v Andrews", citation: "[2009] ZACC 6", court: "Constitutional Court", year: 2009, tags: ["contract law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/6.html", summary: "Arbitration and access to courts; compulsory arbitration clause not inherently unconstitutional." },
  { title: "Telcordia Technologies v Telkom SA", citation: "[2006] ZASCA 112", court: "Supreme Court of Appeal", year: 2006, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2006/112.html", summary: "International arbitration; enforcement of foreign arbitral award under Arbitration Act." },
  { title: "Zhongji Development Construction Engineering v Kambala Mining", citation: "[2015] ZASCA 85", court: "Supreme Court of Appeal", year: 2015, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2015/85.html", summary: "Setting aside arbitral award; gross irregularity in arbitration proceedings as ground for review." },
  { title: "Airports Company SA v ISO Leisure OR Tambo", citation: "[2011] ZASCA 154", court: "Supreme Court of Appeal", year: 2011, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2011/154.html", summary: "Arbitration clause validity; separability doctrine — invalidity of main contract does not invalidate arbitration clause." },

  // ── SURETYSHIP ────────────────────────────────────────────────────────
  { title: "Sapirstein v Anglo African Shipping", citation: "[1978] ZASCA 4", court: "Supreme Court of Appeal", year: 1978, tags: ["banking","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1978/4.html", summary: "Suretyship essentials; surety must have clear intention to bind as guarantor, not merely as co-debtor." },
  { title: "List v Jungers", citation: "[1979] ZASCA 14", court: "Supreme Court of Appeal", year: 1979, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1979/14.html", summary: "Suretyship formalities; writing requirement under General Law Amendment Act for suretyship validity." },
  { title: "Firstrand Bank v Carl Beck Estates", citation: "[2009] ZASCA 85", court: "Supreme Court of Appeal", year: 2009, tags: ["banking","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2009/85.html", summary: "Unlimited suretyship; interpretation of suretyship covering 'all present and future indebtedness'." },
  { title: "Nedbank v Wizard Holdings", citation: "[2010] ZASCA 143", court: "Supreme Court of Appeal", year: 2010, tags: ["banking"], url: "https://www.saflii.org/za/cases/ZASCA/2010/143.html", summary: "Release of co-surety; discharge of one surety does not automatically release remaining sureties." },

  // ── INSURANCE ─────────────────────────────────────────────────────────
  { title: "Mutual & Federal Insurance v Oudtshoorn Municipality", citation: "[1985] ZASCA 26", court: "Supreme Court of Appeal", year: 1985, tags: ["insurance","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1985/26.html", summary: "Insurance warranties; materiality of misrepresentation and duty of utmost good faith (uberrimae fidei)." },
  { title: "Santam v Henery", citation: "[1999] ZASCA 49", court: "Supreme Court of Appeal", year: 1999, tags: ["insurance"], url: "https://www.saflii.org/za/cases/ZASCA/1999/49.html", summary: "Motor vehicle insurance; proximate cause of loss and application of fortuity requirement." },
  { title: "Guardrisk Insurance v Café Chameleon", citation: "[2014] ZASCA 83", court: "Supreme Court of Appeal", year: 2014, tags: ["insurance"], url: "https://www.saflii.org/za/cases/ZASCA/2014/83.html", summary: "Cell captive insurance; insurer's obligation to pay valid claims and policyholder's reasonable expectations." },
  { title: "Bryte Insurance v Sobetwa", citation: "[2018] ZASCA 168", court: "Supreme Court of Appeal", year: 2018, tags: ["insurance","delict"], url: "https://www.saflii.org/za/cases/ZASCA/2018/168.html", summary: "Insurance subrogation; insurer's right to recover from third party after paying insured's claim." },
  { title: "Constantia Insurance v Compusource Aqua", citation: "[2005] ZASCA 41", court: "Supreme Court of Appeal", year: 2005, tags: ["insurance"], url: "https://www.saflii.org/za/cases/ZASCA/2005/41.html", summary: "Professional indemnity insurance; late notification of claim and prejudice to insurer as defence." },
  { title: "Lombard Insurance v Landmark Holdings", citation: "[2010] ZASCA 114", court: "Supreme Court of Appeal", year: 2010, tags: ["insurance"], url: "https://www.saflii.org/za/cases/ZASCA/2010/114.html", summary: "Construction guarantee; demand guarantee vs suretyship — independent obligation of guarantor." },
  { title: "Rand Mutual Assurance v Road Accident Fund", citation: "[2008] ZACC 22", court: "Constitutional Court", year: 2008, tags: ["insurance","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2008/22.html", summary: "Overlap between COIDA and RAF claims; employee injured in road accident during employment." },

  // ── TRUSTS ────────────────────────────────────────────────────────────
  { title: "Land and Agricultural Bank v Parker", citation: "[2004] ZASCA 56", court: "Supreme Court of Appeal", year: 2004, tags: ["company law","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2004/56.html", summary: "Trust independence; alter ego doctrine — when trust treated as mere alter ego of trustee." },
  { title: "Nieuwoudt NO v Vrije Evangeliese Gemeente Welkom", citation: "[2003] ZASCA 58", court: "Supreme Court of Appeal", year: 2003, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2003/58.html", summary: "Trust administration; trustee's duty to act independently and in interests of trust beneficiaries." },
  { title: "Hofer v Kevitt NO", citation: "[1996] ZASCA 3", court: "Supreme Court of Appeal", year: 1996, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1996/3.html", summary: "Inter vivos trust; when founder retains too much control, trust may be regarded as his alter ego." },
  { title: "Van der Merwe NO v Hydraberg Hydraulics CC", citation: "[2010] ZASCA 52", court: "Supreme Court of Appeal", year: 2010, tags: ["company law"], url: "https://www.saflii.org/za/cases/ZASCA/2010/52.html", summary: "Trustee's authority; transactions concluded by trustee without required co-trustee consent voidable." },

  // ── WILLS AND ESTATES ─────────────────────────────────────────────────
  { title: "Ex parte BOE Trust", citation: "[2009] ZACC 15", court: "Constitutional Court", year: 2009, tags: ["family law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/15.html", summary: "Intestate succession for same-sex partners; surviving partner in permanent relationship entitled to inherit." },
  { title: "Moosa v Harneker", citation: "[2017] ZACC 19", court: "Constitutional Court", year: 2017, tags: ["family law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2017/19.html", summary: "Muslim marriages and intestate succession; surviving spouse of Muslim marriage entitled to inherit." },
  { title: "Letsitsa v Roets", citation: "[2019] ZASCA 133", court: "Supreme Court of Appeal", year: 2019, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2019/133.html", summary: "Validity of will; formalities under Wills Act section 2(1)(a) and attestation requirements." },
  { title: "Louw v Louw", citation: "[2018] ZASCA 29", court: "Supreme Court of Appeal", year: 2018, tags: ["family law"], url: "https://www.saflii.org/za/cases/ZASCA/2018/29.html", summary: "Testamentary capacity; undue influence over testator and requirements to set aside will." },
  { title: "Deedat v The Master", citation: "[2015] ZASCA 115", court: "Supreme Court of Appeal", year: 2015, tags: ["family law"], url: "https://www.saflii.org/za/cases/ZASCA/2015/115.html", summary: "Administration of estates; executor's duties and appointment process under Administration of Estates Act." },

  // ── ROAD ACCIDENT FUND ────────────────────────────────────────────────
  { title: "Law Society of SA v Minister of Transport", citation: "[2010] ZACC 25", court: "Constitutional Court", year: 2010, tags: ["delict","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2010/25.html", summary: "RAF Amendment Act capping general damages; constitutionality of legislative limitation on damages claims." },
  { title: "Road Accident Fund v Mphirime", citation: "[2019] ZASCA 166", court: "Supreme Court of Appeal", year: 2019, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2019/166.html", summary: "RAF future medical expenses; actuarial calculation and contingency deductions for future loss." },
  { title: "RAF v Marunga", citation: "[2003] ZASCA 77", court: "Supreme Court of Appeal", year: 2003, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2003/77.html", summary: "Loss of support claim; dependant's claim against RAF for death of breadwinner in motor accident." },

  // ── SHIPPING / ADMIRALTY ───────────────────────────────────────────────
  { title: "MV Snow Crystal: Operators of the MV Snow Crystal v African Coasters", citation: "[2008] ZASCA 27", court: "Supreme Court of Appeal", year: 2008, tags: ["maritime"], url: "https://www.saflii.org/za/cases/ZASCA/2008/27.html", summary: "Admiralty jurisdiction; arrest of vessel and maritime lien under Admiralty Jurisdiction Regulation Act." },
  { title: "MV Taipan: Gillham v MV Taipan", citation: "[2013] ZASCA 107", court: "Supreme Court of Appeal", year: 2013, tags: ["maritime"], url: "https://www.saflii.org/za/cases/ZASCA/2013/107.html", summary: "Associated ship arrest; piercing the corporate veil in admiralty to arrest sister ship." },
  { title: "Transnet v The Owner of MV Stella Tingas", citation: "[2002] ZASCA 133", court: "Supreme Court of Appeal", year: 2002, tags: ["maritime"], url: "https://www.saflii.org/za/cases/ZASCA/2002/133.html", summary: "Port authority's liability; limitation of liability under admiralty law and collision damage." },
];
