// Additional cases: Procurement, Local Government, Interpretation, Unjust Enrichment, Prescription, Evidence, Procedure
module.exports = [
  // ── PUBLIC PROCUREMENT ────────────────────────────────────────────────
  { title: "Steenkamp NO v Provincial Tender Board (EC)", citation: "[2006] ZACC 16", court: "Constitutional Court", year: 2006, tags: ["administrative","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2006/16.html", summary: "Tender Board liability; disappointed tenderer's constitutional damages claim for unfair procurement." },
  { title: "Volvo (SA) v Yssel", citation: "[2009] ZASCA 82", court: "Supreme Court of Appeal", year: 2009, tags: ["administrative"], url: "https://www.saflii.org/za/cases/ZASCA/2009/82.html", summary: "Procurement irregularities; tender participant may challenge award on grounds of material non-compliance." },
  { title: "Dr JS Moroka Municipality v Bethal Chrome Mines", citation: "[2013] ZASCA 20", court: "Supreme Court of Appeal", year: 2013, tags: ["administrative"], url: "https://www.saflii.org/za/cases/ZASCA/2013/20.html", summary: "Municipal procurement; contract concluded without complying with MFMA supply chain management invalid." },
  { title: "Buffalo City Metropolitan Municipality v Asla Construction", citation: "[2019] ZACC 15", court: "Constitutional Court", year: 2019, tags: ["administrative"], url: "https://www.saflii.org/za/cases/ZACC/2019/15.html", summary: "Irregular expenditure; contracts concluded in contravention of procurement requirements may still be valid." },
  { title: "Moseme Road Construction v King Civil Engineering", citation: "[2010] ZASCA 122", court: "Supreme Court of Appeal", year: 2010, tags: ["administrative","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2010/122.html", summary: "Sub-contractor's claim against main contractor in government construction project; payment disputes." },

  // ── LOCAL GOVERNMENT ──────────────────────────────────────────────────
  { title: "Fedsure Life Assurance v Greater Johannesburg TMC", citation: "[1998] ZACC 17", court: "Constitutional Court", year: 1998, tags: ["constitutional","administrative"], url: "https://www.saflii.org/za/cases/ZACC/1998/17.html", summary: "Local government rates; rationality review of municipal levies and principle of legality." },
  { title: "City of Cape Town v Robertson", citation: "[2005] ZACC 2", court: "Constitutional Court", year: 2005, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2005/2.html", summary: "Municipal property rates; constitutionality of rates levied on residential properties." },
  { title: "Matatiele Municipality v President of the RSA", citation: "[2006] ZACC 2", court: "Constitutional Court", year: 2006, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2006/2.html", summary: "Municipal boundary changes; 12th Amendment transferring Matatiele to Eastern Cape required provincial consultation." },
  { title: "Joseph v City of Johannesburg", citation: "[2009] ZACC 30", court: "Constitutional Court", year: 2009, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/30.html", summary: "Right to electricity supply; municipality must follow fair procedure before disconnecting services." },
  { title: "Johannesburg Metropolitan Municipality v Gauteng Development Tribunal", citation: "[2010] ZACC 11", court: "Constitutional Court", year: 2010, tags: ["constitutional","administrative"], url: "https://www.saflii.org/za/cases/ZACC/2010/11.html", summary: "Municipal planning powers; DFA tribunals cannot usurp municipal planning and zoning authority." },
  { title: "City of Tshwane Metropolitan Municipality v Afriforum", citation: "[2016] ZACC 19", court: "Constitutional Court", year: 2016, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2016/19.html", summary: "Municipal language policy; renaming streets in Tshwane and multilingualism obligations." },

  // ── STATUTORY INTERPRETATION ───────────────────────────────────────────
  { title: "Natal Joint Municipal Pension Fund v Endumeni Municipality", citation: "[2012] ZASCA 13", court: "Supreme Court of Appeal", year: 2012, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2012/13.html", summary: "Modern approach to interpretation; unitary exercise considering text, context and purpose." },
  { title: "Bothma-Batho Transport v S Bothma & Seun Transport", citation: "[2013] ZASCA 176", court: "Supreme Court of Appeal", year: 2013, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2013/176.html", summary: "Contract interpretation post-Endumeni; context admissible from outset, not only upon ambiguity." },
  { title: "University of Johannesburg v Auckland Park Theological Seminary", citation: "[2021] ZACC 13", court: "Constitutional Court", year: 2021, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZACC/2021/13.html", summary: "Iterative approach to contract interpretation; text and context in continuous dialogue." },

  // ── UNJUST ENRICHMENT ─────────────────────────────────────────────────
  { title: "McCarthy Retail v Shortdistance Carriers CC", citation: "[2001] ZASCA 83", court: "Supreme Court of Appeal", year: 2001, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2001/83.html", summary: "Enrichment action; general enrichment liability where no specific condictio applies." },
  { title: "Kudu Granite Operations v Caterna", citation: "[2003] ZASCA 59", court: "Supreme Court of Appeal", year: 2003, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2003/59.html", summary: "Enrichment following supervening impossibility; party who has performed may recover on basis of enrichment." },
  { title: "ABSA Bank v Stander t/a Stander & Associates", citation: "[1997] ZASCA 29", court: "Supreme Court of Appeal", year: 1997, tags: ["banking","contract law"], url: "https://www.saflii.org/za/cases/ZASCA/1997/29.html", summary: "Condictio indebiti; mistaken payment by bank recoverable even from innocent recipient." },

  // ── PRESCRIPTION ──────────────────────────────────────────────────────
  { title: "Links v Department of Health (NP)", citation: "[2016] ZACC 10", court: "Constitutional Court", year: 2016, tags: ["delict","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2016/10.html", summary: "Prescription and birth injury; knowledge requirement and when prescription begins to run against minor." },
  { title: "Road Accident Fund v Mdeyide", citation: "[2010] ZACC 18", court: "Constitutional Court", year: 2010, tags: ["delict","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2010/18.html", summary: "RAF claim prescription; section 23(1) of RAF Act three-year limitation period and access to courts." },
  { title: "Makate v Vodacom", citation: "[2016] ZACC 13", court: "Constitutional Court", year: 2016, tags: ["contract law","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2016/13.html", summary: "Please Call Me inventor's claim; enforceability of agreement to negotiate and CEO's authority to bind company." },

  // ── EVIDENCE ──────────────────────────────────────────────────────────
  { title: "S v Zuma", citation: "[1995] ZACC 1", court: "Constitutional Court", year: 1995, tags: ["criminal","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1995/1.html", summary: "Right to silence and privilege against self-incrimination; confession inadmissible unless freely and voluntarily made." },
  { title: "Thint v NDPP", citation: "[2008] ZACC 13", court: "Constitutional Court", year: 2008, tags: ["criminal","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2008/13.html", summary: "Search and seizure warrants; legal professional privilege and requirements for valid warrant." },
  { title: "Bernstein v Bester NO", citation: "[1996] ZACC 2", court: "Constitutional Court", year: 1996, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/1996/2.html", summary: "Right to privacy in corporate context; compelled interrogation under Companies Act limitations." },
  { title: "Magmavax v Safika Holdings", citation: "[2009] ZASCA 154", court: "Supreme Court of Appeal", year: 2009, tags: ["contract law"], url: "https://www.saflii.org/za/cases/ZASCA/2009/154.html", summary: "Parol evidence rule; integration clause and admissibility of extrinsic evidence to contradict written contract." },

  // ── CIVIL PROCEDURE ───────────────────────────────────────────────────
  { title: "Biowatch Trust v Registrar Genetic Resources", citation: "[2009] ZACC 14", court: "Constitutional Court", year: 2009, tags: ["constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2009/14.html", summary: "Costs in constitutional litigation; unsuccessful constitutional litigant against state should not bear costs." },
  { title: "Mukaddam v Pioneer Foods", citation: "[2013] ZACC 23", court: "Constitutional Court", year: 2013, tags: ["consumer","constitutional"], url: "https://www.saflii.org/za/cases/ZACC/2013/23.html", summary: "Class action certification; requirements for representative proceedings under section 38 of Constitution." },
  { title: "Children's Resource Centre Trust v Pioneer Foods", citation: "[2012] ZASCA 182", court: "Supreme Court of Appeal", year: 2012, tags: ["consumer"], url: "https://www.saflii.org/za/cases/ZASCA/2012/182.html", summary: "Class action requirements; certification criteria including common issues, suitable representative, and superiority." },
  { title: "Camps Bay Ratepayers v Harrison", citation: "[2010] ZACC 19", court: "Constitutional Court", year: 2010, tags: ["administrative"], url: "https://www.saflii.org/za/cases/ZACC/2010/19.html", summary: "Locus standi in own interest; property owners' standing to challenge building plan approvals." },
  { title: "Member of the Executive Council for Health v Mkhwanazi", citation: "[2016] ZASCA 176", court: "Supreme Court of Appeal", year: 2016, tags: ["delict"], url: "https://www.saflii.org/za/cases/ZASCA/2016/176.html", summary: "Birth injury litigation; cerebral palsy from delayed caesarean section and causation in medical negligence." },
];
