// server/pdf.js
// PDFKit document generation for LawPath SA.
// Produces tenant-branded legal documents with letterhead, body, and footer.

const PDFDocument = require("pdfkit");

const BRAND_GREEN = "#1f6f5b";
const BRAND_DARK = "#10241f";
const BRAND_MUTED = "#61706b";
const BRAND_GOLD = "#b8860b";

/**
 * Generate a legal contract PDF as a Buffer.
 * @param {object} options
 * @param {string} options.title - Document title
 * @param {string} options.body - Full document text body
 * @param {object} options.tenantProfile - Firm name, address, phone, LPC number, logo
 * @param {string[]} options.parties - Party names for cover page
 * @param {object[]} options.signatories - [{ name, role, signedAt, signatureDataUri }]
 * @param {string} options.matterRef - Matter reference number
 * @param {string} options.documentType - e.g. "Offer to Purchase"
 * @param {boolean} options.includeReviewWarning - Show attorney review disclaimer
 * @returns {Promise<Buffer>}
 */
async function generateContractPdf(options) {
  const {
    title = "Legal Document",
    body = "",
    tenantProfile = {},
    parties = [],
    signatories = [],
    matterRef = "",
    documentType = "Contract",
    includeReviewWarning = true
  } = options;

  // Pre-load logo buffer before entering the synchronous PDFKit stream
  let logoBuffer = null;
  const logoSrc = tenantProfile.logoDataUrl || tenantProfile.logoPublicUrl || "";
  if (logoSrc) {
    try {
      if (logoSrc.startsWith("data:image")) {
        const base64Data = logoSrc.replace(/^data:image\/\w+;base64,/, "");
        logoBuffer = Buffer.from(base64Data, "base64");
      } else if (logoSrc.startsWith("http")) {
        const resp = await fetch(logoSrc);
        if (resp.ok) {
          logoBuffer = Buffer.from(await resp.arrayBuffer());
        }
      }
    } catch {
      logoBuffer = null;
    }
  }

  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: "A4", margin: 60, info: { Title: title, Author: tenantProfile.tradingName || "LawPath SA" } });

    doc.on("data", chunk => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 120;
    const firmName = tenantProfile.tradingName || "LawPath SA";

    // ── LETTERHEAD ──────────────────────────────────────────────────────────
    // Logo (top-right corner, max 120×44 pt)
    if (logoBuffer) {
      try {
        doc.image(logoBuffer, doc.page.width - 180, 52, { fit: [120, 44] });
      } catch {
        // logo rendering failed; fall through to text-only header
      }
    }

    // Firm name
    doc.fontSize(16).fillColor(BRAND_GREEN).font("Helvetica-Bold").text(firmName, 60, 60);

    // Firm details line
    const addressParts = [
      tenantProfile.addressLine1, tenantProfile.city,
      tenantProfile.phone, tenantProfile.lpcRegistrationNumber ? `LPC: ${tenantProfile.lpcRegistrationNumber}` : null
    ].filter(Boolean);

    doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica").text(addressParts.join("  |  "), 60, 80);

    // Horizontal rule
    doc.moveTo(60, 96).lineTo(doc.page.width - 60, 96).strokeColor(BRAND_GREEN).lineWidth(1.5).stroke();

    // Document title block
    doc.moveDown(2);
    doc.fontSize(13).fillColor(BRAND_DARK).font("Helvetica-Bold").text(title.toUpperCase(), { align: "center" });

    if (matterRef) {
      doc.fontSize(9).fillColor(BRAND_MUTED).font("Helvetica").text(`Matter reference: ${matterRef}`, { align: "center" });
    }

    doc.text(`Date: ${new Date().toLocaleDateString("en-ZA", { day: "2-digit", month: "long", year: "numeric" })}`, { align: "center" });
    doc.moveDown(1);

    // Parties section
    if (parties.length > 0) {
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#dce4df").lineWidth(0.5).stroke();
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor(BRAND_MUTED).font("Helvetica").text("PARTIES", { continued: false });
      doc.moveDown(0.3);
      for (const party of parties) {
        doc.fontSize(9).fillColor(BRAND_DARK).font("Helvetica").text(`• ${party}`);
      }
      doc.moveDown(1);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#dce4df").lineWidth(0.5).stroke();
      doc.moveDown(1);
    }

    // ── ATTORNEY REVIEW WARNING ────────────────────────────────────────────
    if (includeReviewWarning) {
      const warningY = doc.y;
      doc.rect(60, warningY, pageWidth, 36).fillColor("#fdf9ec").fill();
      doc.fontSize(8).fillColor(BRAND_GOLD).font("Helvetica-Bold")
        .text("⚠ ATTORNEY REVIEW REQUIRED", 68, warningY + 6);
      doc.fontSize(7.5).fillColor(BRAND_DARK).font("Helvetica")
        .text("This document was generated by LawPath SA and must be reviewed by a qualified South African attorney before signing or sending to any party. This is not legal advice.", 68, warningY + 18, { width: pageWidth - 16 });
      doc.moveDown(2.2);
    }

    // ── DOCUMENT BODY ──────────────────────────────────────────────────────
    const bodyLines = body.split("\n");
    let inHeading = false;

    for (const line of bodyLines) {
      const trimmed = line.trim();
      if (!trimmed) {
        doc.moveDown(0.4);
        inHeading = false;
        continue;
      }

      // Detect section headings (ALL CAPS lines or numbered headings like "1. DEFINITIONS")
      const isHeading = /^(\d+\.|[A-Z\s]{6,})$/.test(trimmed) || /^[A-Z\s]+:$/.test(trimmed);

      if (isHeading) {
        if (doc.y > doc.page.height - 120) doc.addPage();
        doc.moveDown(0.5);
        doc.fontSize(9.5).fillColor(BRAND_GREEN).font("Helvetica-Bold").text(trimmed, { width: pageWidth });
        doc.moveDown(0.3);
      } else {
        if (doc.y > doc.page.height - 80) doc.addPage();
        doc.fontSize(9).fillColor(BRAND_DARK).font("Helvetica").text(trimmed, { width: pageWidth, lineGap: 2 });
      }
    }

    // ── SIGNATURE BLOCKS ───────────────────────────────────────────────────
    if (signatories.length > 0) {
      if (doc.y > doc.page.height - 220) doc.addPage();
      doc.moveDown(2);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor(BRAND_GREEN).lineWidth(1).stroke();
      doc.moveDown(1);
      doc.fontSize(10).fillColor(BRAND_GREEN).font("Helvetica-Bold").text("SIGNATURES");
      doc.moveDown(0.8);

      for (const sig of signatories) {
        if (doc.y > doc.page.height - 130) doc.addPage();

        const sigBlockY = doc.y;

        // Signature image or line
        if (sig.signatureDataUri && sig.signatureDataUri.startsWith("data:image")) {
          try {
            const base64Data = sig.signatureDataUri.replace(/^data:image\/\w+;base64,/, "");
            const imgBuffer = Buffer.from(base64Data, "base64");
            doc.image(imgBuffer, 60, sigBlockY, { width: 160, height: 50 });
          } catch {
            doc.moveTo(60, sigBlockY + 45).lineTo(220, sigBlockY + 45).strokeColor(BRAND_DARK).lineWidth(0.8).stroke();
          }
        } else {
          doc.moveTo(60, sigBlockY + 45).lineTo(220, sigBlockY + 45).strokeColor(BRAND_DARK).lineWidth(0.8).stroke();
        }

        doc.y = sigBlockY + 50;
        doc.fontSize(9).fillColor(BRAND_DARK).font("Helvetica-Bold").text(sig.signatoryName || sig.name || "Signatory");
        doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica").text(sig.role || "Party");
        if (sig.signedAt) {
          doc.text(`Signed: ${new Date(sig.signedAt).toLocaleString("en-ZA")}`);
        }
        if (sig.signatoryIdNumber || sig.idNumber) {
          doc.text(`ID: ${sig.signatoryIdNumber || sig.idNumber}`);
        }
        doc.moveDown(1.2);
      }

      // ECTA statement
      doc.fontSize(7.5).fillColor(BRAND_MUTED).font("Helvetica")
        .text("This document was executed using Advanced Electronic Signatures (AES) in compliance with the Electronic Communications and Transactions Act 25 of 2002 (ECTA). The electronic signatures above are legally binding on the parties.", { width: pageWidth });
    } else {
      // Blank signature lines for manual execution
      if (doc.y > doc.page.height - 200) doc.addPage();
      doc.moveDown(2);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor(BRAND_GREEN).lineWidth(1).stroke();
      doc.moveDown(1);
      doc.fontSize(10).fillColor(BRAND_GREEN).font("Helvetica-Bold").text("SIGNATURES");
      doc.moveDown(1.5);

      const sigLineY = doc.y;
      doc.moveTo(60, sigLineY).lineTo(240, sigLineY).strokeColor(BRAND_DARK).lineWidth(0.8).stroke();
      doc.moveTo(doc.page.width - 240, sigLineY).lineTo(doc.page.width - 60, sigLineY).strokeColor(BRAND_DARK).lineWidth(0.8).stroke();

      doc.y = sigLineY + 6;
      doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica").text("Signature & date", 60, doc.y);
      doc.text("Signature & date", doc.page.width - 240, doc.y);
    }

    // ── FOOTER (on each page) ──────────────────────────────────────────────
    const pageCount = doc.bufferedPageRange();
    for (let i = 0; i < doc._pageBuffer.length; i++) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 40;
      doc.moveTo(60, footerY - 8).lineTo(doc.page.width - 60, footerY - 8).strokeColor("#dce4df").lineWidth(0.5).stroke();
      doc.fontSize(7).fillColor(BRAND_MUTED).font("Helvetica")
        .text(`${firmName}  |  Generated by LawPath SA  |  Page ${i + 1}`, 60, footerY, { width: pageWidth, align: "center" });
    }

    doc.end();
  });
}

/**
 * Generate a trust account statement PDF.
 */
async function generateTrustStatementPdf({ tenantProfile, transactions, periodLabel, balanceCents }) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: "A4", margin: 60 });
    doc.on("data", c => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const money = (cents) => `R ${(cents / 100).toLocaleString("en-ZA", { minimumFractionDigits: 2 })}`;
    const firmName = tenantProfile?.tradingName || "LawPath SA";
    const pageWidth = doc.page.width - 120;

    // Header
    doc.fontSize(16).fillColor(BRAND_GREEN).font("Helvetica-Bold").text(firmName, 60, 60);
    doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica").text("SECTION 86 TRUST ACCOUNT STATEMENT", 60, 80);
    doc.moveTo(60, 96).lineTo(doc.page.width - 60, 96).strokeColor(BRAND_GREEN).lineWidth(1.5).stroke();

    doc.moveDown(2);
    doc.fontSize(12).fillColor(BRAND_DARK).font("Helvetica-Bold").text(`Trust Account Statement — ${periodLabel}`, { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor(BRAND_MUTED).font("Helvetica").text(`Generated: ${new Date().toLocaleDateString("en-ZA")}`, { align: "center" });
    doc.moveDown(1.5);

    // Balance
    doc.rect(60, doc.y, pageWidth, 36).fillColor("#eaf1ed").fill();
    doc.fontSize(10).fillColor(BRAND_GREEN).font("Helvetica-Bold").text(`Trust Balance: ${money(balanceCents)}`, 68, doc.y - 28);
    doc.moveDown(1.5);

    // Table header
    const cols = [60, 120, 230, 370, 460];
    doc.fontSize(8).fillColor(BRAND_DARK).font("Helvetica-Bold");
    doc.rect(60, doc.y, pageWidth, 18).fillColor("#f0f4f1").fill();
    doc.fillColor(BRAND_DARK);
    ["Date", "Client", "Description", "Type", "Amount"].forEach((h, i) => {
      doc.text(h, cols[i], doc.y - 14, { width: (cols[i + 1] || doc.page.width - 60) - cols[i] - 4 });
    });
    doc.moveDown(0.5);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#dce4df").lineWidth(0.5).stroke();

    // Rows
    for (const tx of (transactions || [])) {
      if (doc.y > doc.page.height - 80) doc.addPage();
      const rowY = doc.y + 2;
      const isCredit = ["receipt", "transfer_in"].includes(tx.entryType);
      const amtText = (isCredit ? "+" : "-") + money(tx.amountCents);
      doc.fontSize(8).fillColor(BRAND_DARK).font("Helvetica");
      doc.text(tx.valueDate || "", cols[0], rowY, { width: cols[1] - cols[0] - 4 });
      doc.text((tx.clientName || "").slice(0, 20), cols[1], rowY, { width: cols[2] - cols[1] - 4 });
      doc.text((tx.description || "").slice(0, 40), cols[2], rowY, { width: cols[3] - cols[2] - 4 });
      doc.text(tx.entryType || "", cols[3], rowY, { width: cols[4] - cols[3] - 4 });
      doc.fillColor(isCredit ? BRAND_GREEN : "#9d4452").text(amtText, cols[4], rowY, { width: doc.page.width - 60 - cols[4] });
      doc.moveDown(0.9);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#f0f4f1").lineWidth(0.3).stroke();
    }

    doc.moveDown(1);
    doc.fontSize(7.5).fillColor(BRAND_MUTED).font("Helvetica")
      .text("This statement is produced under Section 86(4) of the Legal Practice Act 28 of 2014. It must be reconciled against the bank statement monthly.", { width: pageWidth });

    doc.end();
  });
}

/**
 * Generate a South African tax invoice PDF.
 * @param {object} options
 * @param {object}   options.invoice       - Invoice record from DB
 * @param {object[]} options.lineItems     - invoice_line_items rows
 * @param {object[]} options.payments      - invoice_payments rows
 * @param {object}   options.tenantProfile - Firm details for letterhead
 */
async function generateInvoicePdf({ invoice, lineItems = [], payments = [], tenantProfile = {} }) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: "A4", margin: 60 });
    doc.on("data", c => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const money = (cents) =>
      `R ${(Number(cents || 0) / 100).toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    const firmName = tenantProfile.tradingName || "LawPath SA";
    const pageWidth = doc.page.width - 120;
    const rightCol = doc.page.width - 60;

    // ── LETTERHEAD ────────────────────────────────────────────────────────────
    doc.fontSize(17).fillColor(BRAND_GREEN).font("Helvetica-Bold").text(firmName, 60, 58);

    const addrParts = [
      tenantProfile.addressLine1, tenantProfile.city,
      tenantProfile.phone, tenantProfile.website
    ].filter(Boolean);
    doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica").text(addrParts.join("  |  "), 60, 79, { width: 320 });

    // TAX INVOICE label (right-aligned)
    doc.fontSize(18).fillColor(BRAND_DARK).font("Helvetica-Bold").text("TAX INVOICE", 60, 58, { width: pageWidth, align: "right" });
    doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica")
      .text(tenantProfile.vatNumber ? `VAT No: ${tenantProfile.vatNumber}` : "", 60, 79, { width: pageWidth, align: "right" });
    if (tenantProfile.lpcRegistrationNumber) {
      doc.text(`LPC: ${tenantProfile.lpcRegistrationNumber}`, 60, 89, { width: pageWidth, align: "right" });
    }

    doc.moveTo(60, 100).lineTo(rightCol, 100).strokeColor(BRAND_GREEN).lineWidth(1.5).stroke();

    // ── INVOICE META (two-column) ─────────────────────────────────────────────
    const metaY = 112;
    // Left: bill-to
    doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica-Bold").text("BILLED TO", 60, metaY);
    doc.fontSize(9).fillColor(BRAND_DARK).font("Helvetica-Bold").text(invoice.client_name || invoice.clientName, 60, metaY + 12);
    if (invoice.matter_ref || invoice.matterRef) {
      doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica")
        .text(`Matter: ${invoice.matter_ref || invoice.matterRef}`, 60, metaY + 24);
    }

    // Right: invoice details table
    const detailX = 370;
    const detailRows = [
      ["Invoice No:", invoice.invoice_number || invoice.invoiceNumber],
      ["Invoice Date:", invoice.issued_at ? new Date(invoice.issued_at).toLocaleDateString("en-ZA") : new Date().toLocaleDateString("en-ZA")],
      ["Due Date:", invoice.due_at ? new Date(invoice.due_at).toLocaleDateString("en-ZA") : "30 days"],
    ];
    if (invoice.payment_ref || invoice.paymentRef) {
      detailRows.push(["Payment Ref:", invoice.payment_ref || invoice.paymentRef]);
    }
    let detailRowY = metaY;
    for (const [label, value] of detailRows) {
      doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica").text(label, detailX, detailRowY, { width: 80 });
      doc.fontSize(8).fillColor(BRAND_DARK).font("Helvetica-Bold").text(String(value || ""), detailX + 82, detailRowY, { width: 108 });
      detailRowY += 12;
    }

    doc.moveTo(60, metaY + 56).lineTo(rightCol, metaY + 56).strokeColor("#dce4de").lineWidth(0.5).stroke();

    // ── LINE ITEMS TABLE ──────────────────────────────────────────────────────
    const tableY = metaY + 64;
    const cols = { date: 60, desc: 110, earner: 250, dur: 310, rate: 360, excl: 415, vat: 467, total: 517 };

    // Table header
    doc.rect(60, tableY, pageWidth, 16).fillColor("#eef2ee").fill();
    doc.fontSize(7.5).fillColor(BRAND_DARK).font("Helvetica-Bold");
    doc.text("Date",       cols.date,  tableY + 4, { width: 48 });
    doc.text("Description",cols.desc,  tableY + 4, { width: 138 });
    doc.text("Earner",     cols.earner,tableY + 4, { width: 58 });
    doc.text("Hrs",        cols.dur,   tableY + 4, { width: 48, align: "right" });
    doc.text("Rate",       cols.rate,  tableY + 4, { width: 53, align: "right" });
    doc.text("Excl. VAT",  cols.excl,  tableY + 4, { width: 50, align: "right" });
    doc.text("VAT",        cols.vat,   tableY + 4, { width: 48, align: "right" });
    doc.text("Total",      cols.total, tableY + 4, { width: 43, align: "right" });

    let rowY = tableY + 18;
    let rowIndex = 0;
    for (const item of lineItems) {
      if (rowY > doc.page.height - 120) { doc.addPage(); rowY = 60; }
      if (rowIndex % 2 === 0) {
        doc.rect(60, rowY - 1, pageWidth, 15).fillColor("#f8faf7").fill();
      }
      const dur = item.duration_minutes > 0
        ? (item.duration_minutes / 60).toFixed(2)
        : (item.is_disbursement ? "—" : "");
      const rate = item.rate_cents > 0 ? money(item.rate_cents) : "—";
      doc.fontSize(7.5).fillColor(BRAND_DARK).font("Helvetica");
      doc.text(item.entry_date ? new Date(item.entry_date).toLocaleDateString("en-ZA") : "", cols.date, rowY + 2, { width: 48 });
      doc.text((item.description || "").slice(0, 55), cols.desc, rowY + 2, { width: 138 });
      doc.text((item.fee_earner_name || "").slice(0, 18), cols.earner, rowY + 2, { width: 58 });
      doc.text(dur,        cols.dur,   rowY + 2, { width: 48,  align: "right" });
      doc.text(rate,       cols.rate,  rowY + 2, { width: 53,  align: "right" });
      doc.text(money(item.amount_cents),      cols.excl,  rowY + 2, { width: 50,  align: "right" });
      doc.text(money(item.vat_cents),         cols.vat,   rowY + 2, { width: 48,  align: "right" });
      doc.text(money(Number(item.amount_cents) + Number(item.vat_cents)), cols.total, rowY + 2, { width: 43, align: "right" });
      rowY += 15;
      rowIndex++;
      doc.moveTo(60, rowY).lineTo(rightCol, rowY).strokeColor("#f0f4f1").lineWidth(0.3).stroke();
    }

    // ── TOTALS ────────────────────────────────────────────────────────────────
    rowY += 6;
    const totalsX = 380;
    const totalsW = rightCol - totalsX - 4;
    const totals = [
      ["Subtotal (excl. VAT):", money(invoice.subtotal_cents || invoice.subtotalCents || 0)],
      ["VAT (15%):",            money(invoice.vat_cents || invoice.vatCents || 0)],
    ];
    const paidCents = Number(invoice.paid_cents || invoice.paidCents || 0);
    const totalCents = Number(invoice.amount_cents || invoice.amountCents || 0);
    if (paidCents > 0) totals.push(["Less payments received:", `(${money(paidCents)})`]);

    for (const [label, value] of totals) {
      if (rowY > doc.page.height - 80) { doc.addPage(); rowY = 60; }
      doc.fontSize(8.5).fillColor(BRAND_MUTED).font("Helvetica").text(label, totalsX, rowY, { width: 140 });
      doc.fillColor(BRAND_DARK).font("Helvetica-Bold").text(value, totalsX, rowY, { width: totalsW, align: "right" });
      rowY += 14;
    }

    // Grand total box
    doc.rect(totalsX - 4, rowY, totalsW + 8, 22).fillColor(BRAND_GREEN).fill();
    const balance = paidCents > 0 ? totalCents - paidCents : totalCents;
    const balanceLabel = paidCents > 0 ? "BALANCE DUE:" : "TOTAL DUE:";
    doc.fontSize(10).fillColor("#ffffff").font("Helvetica-Bold")
      .text(balanceLabel, totalsX, rowY + 6, { width: 140 });
    doc.text(money(balance), totalsX, rowY + 6, { width: totalsW, align: "right" });
    rowY += 34;

    // ── PAYMENTS RECEIVED ─────────────────────────────────────────────────────
    if (payments.length > 0) {
      if (rowY > doc.page.height - 80) { doc.addPage(); rowY = 60; }
      doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica-Bold").text("PAYMENTS RECEIVED", 60, rowY);
      rowY += 12;
      for (const pmt of payments) {
        doc.fontSize(8).fillColor(BRAND_DARK).font("Helvetica")
          .text(`${new Date(pmt.payment_date).toLocaleDateString("en-ZA")}  |  ${pmt.payment_method}${pmt.reference ? `  |  Ref: ${pmt.reference}` : ""}  |  ${money(pmt.amount_cents)}`, 60, rowY, { width: pageWidth });
        rowY += 12;
      }
      rowY += 4;
    }

    // ── NOTES & TERMS ─────────────────────────────────────────────────────────
    if (rowY > doc.page.height - 100) { doc.addPage(); rowY = 60; }
    doc.moveTo(60, rowY).lineTo(rightCol, rowY).strokeColor("#dce4de").lineWidth(0.5).stroke();
    rowY += 8;
    if (invoice.notes) {
      doc.fontSize(8).fillColor(BRAND_MUTED).font("Helvetica-Bold").text("NOTES", 60, rowY);
      rowY += 10;
      doc.fontSize(7.5).fillColor(BRAND_DARK).font("Helvetica").text(invoice.notes, 60, rowY, { width: pageWidth });
      rowY += doc.heightOfString(invoice.notes, { width: pageWidth, fontSize: 7.5 }) + 8;
    }
    const terms = invoice.terms || "Payment is due within 30 days of invoice date.";
    doc.fontSize(7.5).fillColor(BRAND_MUTED).font("Helvetica").text(terms, 60, rowY, { width: pageWidth });

    // ── FOOTER ────────────────────────────────────────────────────────────────
    for (let i = 0; i < doc._pageBuffer.length; i++) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 38;
      doc.moveTo(60, footerY - 6).lineTo(rightCol, footerY - 6).strokeColor("#dce4de").lineWidth(0.5).stroke();
      doc.fontSize(7).fillColor(BRAND_MUTED).font("Helvetica")
        .text(`${firmName}  |  ${invoice.invoice_number || invoice.invoiceNumber}  |  Generated by LawPath SA  |  Page ${i + 1}`, 60, footerY, { width: pageWidth, align: "center" });
    }

    doc.end();
  });
}

module.exports = { generateContractPdf, generateTrustStatementPdf, generateInvoicePdf };
