// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lawpath-landing/DarkPrestige.tsx": () => import("../components/mockups/lawpath-landing/DarkPrestige.tsx"),
  "./components/mockups/lawpath-landing/ExecutiveEdge.tsx": () => import("../components/mockups/lawpath-landing/ExecutiveEdge.tsx"),
  "./components/mockups/lawpath-landing/WhiteGlove.tsx": () => import("../components/mockups/lawpath-landing/WhiteGlove.tsx")
};
